Repository caicloud/cyclone, pull requests merged in 2018-06, with the labels that each got.

#500 perf(project):validate token from getting repos just for once
  pkg/scm/provider/github.go
  pkg/scm/provider/gitlab.go
  pkg/scm/scm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#497 feat(api):add recent record info while getting pipeline
  pkg/api/types.go
  pkg/server/manager/pipeline.go
  pkg/server/router/pipeline.go
  pkg/server/router/pipelineRecord.go
Labels: caicloud-cla: yes, lgtm, release-note-none, size/L

#507 Merge branch 'worker-enhancement' into 'master'
  api/server/server.go
  cloud/controller.go
  cloud/docker.go
  cloud/k8s.go
  cloud/types.go
  cmd/server/options.go
  cmd/server/server.go
  cmd/worker/options.go
  cmd/worker/options/options.go
  cmd/worker/options/options_test.go
  cmd/worker/options/quota.go
  cmd/worker/worker.go
  pkg/api/types.go
  pkg/cloud/docker/docker.go
  pkg/cloud/errors.go
  pkg/cloud/kubernetes/kubernetes.go
  pkg/cloud/provider.go
  pkg/event/manager.go
  pkg/server/manager/cloud.go
  pkg/server/manager/pipeline.go
  pkg/server/router/cloud.go
  pkg/server/router/health_check.go
  pkg/server/router/router.go
  pkg/store/cloud.go
  pkg/store/store.go
  pkg/worker/options.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#492 feat:support push event type webhook
  pkg/scm/provider/github.go
  pkg/server/router/webhook.go
  pkg/util/gitlab/gitlab.go
  pkg/util/gitlab/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#453 test:add tests for project
  .travis.yml
  scripts/e2e-docker.sh
  scripts/e2e-k8s.sh
  tests/README.md
  tests/common/log.go
  tests/common/project.go
  tests/common/service.go
  tests/common/setup.go
  tests/common/utils.go
  tests/common/version.go
  tests/project/project_suite_test.go
  tests/project/project_test.go
  tests/service/service_suite_test.go
  tests/service/service_test.go
  tests/version/version_suite_test.go
  tests/version/version_test.go
  tests/yaml/yaml_suite_test.go
  tests/yaml/yaml_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#510 feat: support to skip package stage
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#512 fix(*): e2e test failure
  notify/provider/email.go
  scripts/e2e-docker.sh
  scripts/e2e-k8s.sh
  tests/common/setup.go
  tests/project/project_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#514 fix(Dockerfile):remove http/web
  build/server/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#515 feat:support username/password auth for k8s cluster
  docs/api/v1/api.md
  pkg/api/helper_test.go
  pkg/api/types.go
  pkg/cloud/docker/docker.go
  pkg/cloud/kubernetes/kubernetes.go
  pkg/server/manager/cloud.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
