Repository caicloud/cyclone, pull requests merged in 2018-07, with the labels that each got.

#520 fix(worker):submodules can not be checkout while cloning repo
  pkg/worker/scm/provider/git.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#521 fix(worker):submodules can not be checkout while cloning repo
  worker/vcs/provider/git.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#508 docs: update developer guide
  docs/architecture.png
  docs/developer-guide.md
  docs/developer-guide_zh-CN.md
  docs/flow.png
  docs/images/architecture-2.7.png
  docs/images/architecture-old.png
  docs/images/work-flow-2.7.png
  scripts/build-server.sh
  scripts/build-worker.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#509 docs:update README and functions
  README.md
  README_zh-CN.md
  caicloud_e2e-test.yml
  caicloud_unit-test.yml
  docs/caicloud-yml-introduction.md
  docs/caicloud-yml-introduction_zh-CN.md
  docs/caicloud-yml-reference.md
  docs/caicloud-yml-reference_zh-CN.md
  docs/create_service.png
  docs/create_version.png
  docs/dependency.png
  docs/deployment.png
  docs/functions.md
  docs/functions_zh-CN.md
  docs/images/codeCheckout.png
  docs/images/create_project.png
  docs/images/imageBuild.png
  docs/images/imageRelease.png
  docs/images/integration.png
  docs/images/list_projects.png
  docs/images/logStream.png
  docs/images/logo.jpeg
  docs/images/package.png
  docs/images/webhook.png
  docs/list_services.png
  docs/logs.png
  docs/pagging.png
  docs/quota.png
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#522 feat: add oauth api for gitlab
  pkg/api/types.go
  pkg/scm/provider/github.go
  pkg/scm/provider/gitlab.go
  pkg/scm/provider/helper.go
  pkg/scm/provider/svn.go
  pkg/scm/scm.go
  pkg/server/router/oauth.go
  pkg/server/router/router.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#503 docs:update quick-start document
  docs/quick-start.md
  docs/quick-start_zh-CN.md
  pkg/worker/stage/stage.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#525 feat:support build speedup for gradle
  pkg/api/types.go
  pkg/event/manager.go
  pkg/worker/stage/stage.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#531 fix(worker): worker create tag failed
  cmd/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#526 feat:support configuring resource quota for cyclone worker
  docs/api/v1/api.md
  pkg/api/types.go
  pkg/cloud/kubernetes/kubernetes.go
  pkg/event/manager.go
  pkg/event/manager_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#534 chore:change WorkerConfig.Quota's type from struct to pointer
  pkg/api/types.go
  pkg/docker/client.go
  pkg/event/manager.go
  pkg/event/manager_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#536 feat(worker):update worker storage driver from vfs to overlay
  build/worker/start.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#535 feat(worker):update dind version from 1.13.1 to 17.03.1-ce
  build/worker/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#533 feat:push event webhook support configuring target branches
  pkg/server/router/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#538 fix(docs):router.InitRouters() must be called before InstallSwaggerService
  api/server/server.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#541 fix:pod should be deleted while creating worker timeout
  pkg/cloud/kubernetes/kubernetes.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#543 fix(worker):integration does not work because server start failed
  pkg/docker/client.go
  pkg/worker/stage/stage.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
