Repository caicloud/cyclone, pull requests merged in 2018-05, with the labels that each got.

#460 fix(webhook):executing pipeline failed when the trigger is PR webhook
  pkg/server/router/webhook.go
  pkg/worker/scm/provider/git.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#462 chore(*): add zhujian into owner
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#465 fix(#463): add log for each request
  pkg/server/router/router.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#466 fix:add 'repository' to support update image registry
  pkg/api/types.go
  pkg/worker/stage/stage.go
  pkg/worker/stage/stage_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#467 fix(#464): refactor cloud type
  cloud/controller.go
  cloud/docker.go
  cloud/k8s.go
  cloud/types.go
  pkg/event/manager.go
  pkg/server/manager/cloud.go
  pkg/server/router/cloud.go
  pkg/store/cloud.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#362 feat(docs): update the log API for stage log
  docs/api/v1/api.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#468 feat: add oauth api for creating project
  .gitignore
  pkg/api/types.go
  pkg/scm/provider/github.go
  pkg/scm/provider/gitlab.go
  pkg/scm/provider/helper.go
  pkg/scm/scm.go
  pkg/server/router/router.go
  pkg/server/router/scm.go
  store/scm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#472 fix(oauth): fix the bug of returning wrong gitlab server url
  pkg/scm/provider/gitlab.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#471 fix(mongo):can not get data from mongo while there are two pieces of …
  pkg/store/pipeline.go
  pkg/store/project.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#473 fix(store): fix id of cloud
  pkg/store/cloud.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#476 feat(api): add cloud api doc
  docs/api/v1/api.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#479 chore(typo): fix typo
  pkg/store/store.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#475 refactor cloud for worker
  api/server/server.go
  cloud/controller.go
  cloud/docker.go
  cloud/k8s.go
  cloud/types.go
  cmd/server/options.go
  cmd/server/server.go
  cmd/worker/options.go
  cmd/worker/options/options.go
  cmd/worker/options/options_test.go
  cmd/worker/options/quota.go
  cmd/worker/worker.go
  pkg/api/types.go
  pkg/cloud/docker/docker.go
  pkg/cloud/errors.go
  pkg/cloud/kubernetes/kubernetes.go
  pkg/cloud/provider.go
  pkg/event/manager.go
  pkg/server/manager/cloud.go
  pkg/server/manager/pipeline.go
  pkg/server/router/cloud.go
  pkg/server/router/health_check.go
  pkg/server/router/router.go
  pkg/store/cloud.go
  pkg/store/store.go
  pkg/worker/options.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#478 fix(mongo):can not get data from mongo while there are two pieces of data
  store/pipeline.go
  store/project.go
  store/scm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#474 feat(docker):support builder images from docker hub
  pkg/docker/client.go
  pkg/worker/stage/stage_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#469 fix(name conflict):avoid name conflict when generate it from alias
  pkg/server/manager/pipeline.go
  pkg/server/manager/project.go
  pkg/util/slugify/slugify.go
  pkg/util/slugify/slugify_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#489 fix:build container's main process exited while build commands are ru…
  pkg/docker/client.go
  pkg/worker/stage/stage.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#493 fix:logs are not deleted while deleting related resource
  pkg/server/manager/pipeline.go
  pkg/server/manager/pipelineRecord.go
  pkg/server/manager/project.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#494 feat:support pipeline record rotation
  api/server/options.go
  api/server/server.go
  pkg/server/manager/pipelineRecord.go
  pkg/server/router/router.go
  pkg/store/pipelineRecord.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#495 fix(worker):change container start entrypoint
  pkg/docker/client.go
  pkg/docker/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
