Repository caicloud/cyclone, pull requests merged in 2018-12, with the labels that each got.

#637 feat(api): add api to support list Dockerfiles in the repo
  docs/api/v1/api.md
  pkg/api/v1/descriptor/project.go
  pkg/api/v1/handler/project.go
  pkg/scm/provider/github/github.go
  pkg/scm/provider/gitlab/gitlabv3.go
  pkg/scm/provider/gitlab/gitlabv4.go
  pkg/scm/provider/svn/svn.go
  pkg/scm/scm.go
  pkg/server/manager/project.go
  pkg/worker/stage/helper_test.go
  pkg/worker/stage/stage_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#638 feat: support adding registry cert files to cyclone worker
  build/worker/start.sh
  pkg/cloud/docker/docker.go
  pkg/cloud/kubernetes/kubernetes.go
  pkg/cloud/provider.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#636 feat: configure and apply default quota to pod containers
  manifests/cyclone.yaml
  pkg/workflow/controller/config.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/workflowrun/pod.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#641 chore: fix typo
  cmd/worker/worker.go
  pkg/cloud/docker/docker.go
  pkg/cloud/provider.go
  pkg/scm/provider/github/github.go
  pkg/util/os/os.go
  pkg/worker/scm/provider/svn.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#644 fix: timeout processor when wfr not found
  pkg/workflow/workflowrun/timeout.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#645 fix: use correct memory unit in quota
  manifests/cyclone.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#646 fix: resovlers
  build/workflow/resolver/git/entrypoint.sh
  build/workflow/resolver/image/entrypoint.sh
  manifests/examples/ci.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#643 fix: pipeline is stuck when package step execution successfully
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#647 fix(codeScan): optimize code scan
  cmd/server/server.go
  pkg/api/types.go
  pkg/common/constant.go
  pkg/integrate/manager.go
  pkg/integrate/provider/sonar/sonar.go
  pkg/integrate/provider/sonar/sonar_test.go
  pkg/integrate/provider/sonar/testdata/report-task.txt
  pkg/junit/report.go
  pkg/junit/report_test.go
  pkg/server/manager/integration.go
  pkg/server/manager/pipeline.go
  pkg/util/http/errors/format.go
  pkg/worker/common/constant.go
  pkg/worker/integrate/provider/sonar.go
  pkg/worker/scm/manager.go
  pkg/worker/stage/helper.go
  pkg/worker/stage/helper_test.go
  pkg/worker/stage/stage.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#648 feat: support kubeconfig for kubernetes authentication
  Gopkg.lock
  pkg/api/types.go
  pkg/cloud/kubernetes/kubernetes.go
  vendor/github.com/howeyc/gopass/.travis.yml
  vendor/github.com/howeyc/gopass/LICENSE.txt
  vendor/github.com/howeyc/gopass/OPENSOLARIS.LICENSE
  vendor/github.com/howeyc/gopass/README.md
  vendor/github.com/howeyc/gopass/pass.go
  vendor/github.com/howeyc/gopass/pass_test.go
  vendor/github.com/howeyc/gopass/terminal.go
  vendor/github.com/howeyc/gopass/terminal_solaris.go
  vendor/github.com/imdario/mergo/.gitignore
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/CODE_OF_CONDUCT.md
  vendor/github.com/imdario/mergo/LICENSE
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/doc.go
  vendor/github.com/imdario/mergo/issue17_test.go
  vendor/github.com/imdario/mergo/issue23_test.go
  vendor/github.com/imdario/mergo/issue33_test.go
  vendor/github.com/imdario/mergo/issue38_test.go
  vendor/github.com/imdario/mergo/issue50_test.go
  vendor/github.com/imdario/mergo/issue52_test.go
  vendor/github.com/imdario/mergo/issue61_test.go
  vendor/github.com/imdario/mergo/issue64_test.go
  vendor/github.com/imdario/mergo/issue66_test.go
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/merge_appendslice_test.go
  vendor/github.com/imdario/mergo/merge_test.go
  vendor/github.com/imdario/mergo/mergo.go
  vendor/github.com/imdario/mergo/mergo_test.go
  vendor/github.com/imdario/mergo/pr80_test.go
  vendor/github.com/imdario/mergo/pr81_test.go
  vendor/github.com/imdario/mergo/testdata/license.yml
  vendor/github.com/imdario/mergo/testdata/thing.yml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#649 feat: delete sonar project while deleting associated pipeline
  pkg/integrate/manager.go
  pkg/integrate/provider/sonar/sonar.go
  pkg/server/manager/pipeline.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#650 fix(sonarqube): create sonar project failed since pipeline id is empty
  pkg/event/manager.go
  pkg/integrate/manager.go
  pkg/server/manager/pipeline.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#651 improve: make pv and secret optional
  manifests/cyclone.yaml
  manifests/examples/simple.yaml
  pkg/workflow/common/const.go
  pkg/workflow/controller/config.go
  pkg/workflow/workflowrun/pod.go
  pkg/workflow/workflowrun/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#658 test: add some tests for code scanning
  pkg/integrate/provider/fake/fake.go
  pkg/integrate/provider/sonar/sonar_test.go
  pkg/util/os/os_test.go
  pkg/worker/stage/stage_test.go
  pkg/worker/worker_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#656 feat: controll timeout of git clone
  pkg/worker/scm/manager.go
  pkg/worker/scm/provider/git.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#657 fix: can not exec worker by docker-type cloud
  pkg/api/types.go
  scripts/e2e-k8s.sh
  scripts/setup.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#661 fix: support multi dockerfiles for one template
  config/templates/templates.yaml
  pkg/api/types.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#662 chore: delete unused code
  .travis.yml
  build/server/Dockerfile
  cmd/worker/options/options.go
  cmd/worker/options/options_test.go
  notify/interface.go
  notify/manager.go
  notify/manager_test.go
  notify/provider/email.go
  notify/provider/email_test.go
  notify/provider/error.html
  notify/provider/errorchinese.html
  notify/provider/success.html
  notify/provider/successchinese.html
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#660 chore: map timezone of host
  manifests/cyclone.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#663 fix: should use new git resource url to create webhook
  pkg/server/manager/pipeline.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#664 fix: change sonar link from measures to overview
  pkg/integrate/provider/sonar/sonar.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#666 fix: use base64 encoded cert
  .gitignore
  pkg/cloud/kubernetes/kubernetes.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#667 fix(trigger): support timezone for workflowTrigger
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#668 fix: allow user to configure pvc and path in output resource
  Makefile
  manifests/cyclone.yaml
  pkg/workflow/common/const.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
  pkg/workflow/workflowrun/pod.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#669 fix: can not record error message for allow-failure stages
  pkg/api/types.go
  pkg/worker/stage/helper.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#678 fix(trigger): add label for workflowRun created by trigger
  pkg/workflow/common/const.go
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#679 fix: cyclone server address for pod in different ns
  manifests/cyclone.yaml
Labels: caicloud-cla: yes, release-note-none, size/XS

#682 feat(*): project list and detail
  web/.eslintrc
  web/.prettierignore
  web/config/webpack.config.dev.js
  web/config/webpack.config.prod.js
  web/package.json
  web/src/components/project/component/AddProject.js
  web/src/components/project/component/List.js
  web/src/components/project/component/ProjectDetail.js
  web/src/components/project/component/list.js
  web/src/components/project/index.js
  web/src/components/public/detail/Content.js
  web/src/components/public/detail/Head.js
  web/src/components/public/detail/HeadItem.js
  web/src/components/public/detail/index.js
  web/src/components/public/detail/index.md
  web/src/components/public/ellipsisMenu/index.js
  web/src/components/public/ellipsisMenu/index.md
  web/src/components/workflow/component/list.js
  web/src/layout/index.js
  web/src/less/inc.var.less
  web/src/less/index.less
  web/src/less/u-detail.less
  web/src/locale/en-US.json
  web/src/locale/zh-CN.json
  web/src/registerServiceWorker.js
  web/yarn.lock
Labels: caicloud-cla: yes, lgtm, release-note-none, size/XXL

#687 feat(*): add breadcrumb
  web/src/components/project/component/ProjectDetail.js
  web/src/components/workflow/component/list.js
  web/src/layout/Breadcrumb.js
  web/src/layout/index.js
  web/src/store/workflow.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#674 feat(web): add mockServerMiddleware & set api-proxy
  web/config/middleware/mockServerMiddleware.js
  web/config/webpackDevServer.config.js
  web/mock/example.js
  web/package.json
  web/src/api/http.js
Labels: caicloud-cla: yes, lgtm, release-note-none, size/L

#676 chore: add release yaml file
  Makefile
  build/web/Dockerfile
  build/web/Dockerfile.multistage
  release/README.md
  release/cyclone-server.yaml
  release/cyclone-web.yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#693 fix(release): fix cyclone web release
  release/cyclone-web.yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#677 doc: add README.md
  README.md
  docs/images/logo.jpeg
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#686 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
