Repository caicloud/cyclone, pull requests merged in 2018-09, with the labels that each got.

#558 fix: add some prompt message when create scm tag failed
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#562 fix: add some prompt message when create webhook failed
  pkg/server/manager/pipeline.go
  pkg/util/http/errors/format.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#560 feat: add retry logic for code checkout
  pkg/worker/scm/manager.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#563 feat: add value charts
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#566 chore(owner): update owners
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#568 fix: close response body earlier
  pkg/scm/provider/gitlab/gitlab.go
  pkg/worker/cycloneserver/client.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#567 fix: change the url path pipelinetemplates to configtemplates
  docs/api/v1/api.md
  pkg/api/v1/descriptor/template.go
  pkg/api/v1/handler/template.go
  pkg/api/v1/handler/template_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#570 fix: delete notification config failed while updating pipeline
  pkg/server/manager/pipeline.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#572 chore: change service type from NodePort to ClusterIP
  release/README.md
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#574 fix: can not delete pipeline while scm server is unavailable
  pkg/server/manager/pipeline.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#573 feature(webhook-pr):pr webhook support display commit statuses
  docs/api/v1/api.md
  docs/setup.md
  docs/setup_zh-CN.md
  pkg/api/types.go
  pkg/api/v1/handler/webhook.go
  pkg/api/v1/handler/webhook_test.go
  pkg/event/manager.go
  pkg/event/manager_test.go
  pkg/scm/provider/github/github.go
  pkg/scm/provider/gitlab/gitlab.go
  pkg/scm/provider/gitlab/gitlabv3.go
  pkg/scm/provider/gitlab/gitlabv4.go
  pkg/scm/provider/svn/svn.go
  pkg/scm/scm.go
  pkg/server/manager/pipeline.go
  pkg/server/options.go
  pkg/server/server.go
  pkg/util/http/errors/format.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/L

#576 feat: add pipeline record web url for notification
  pkg/api/types.go
  pkg/event/manager.go
  pkg/event/manager_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#577 test: add test cases for collect JUnit test
  pkg/worker/junit/report_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#578 chore(release): update release yaml typo
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#580 chore(templates): add commands for collecting golang JUnit test reports
  config/templates/templates.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#582 chore(release): update release yaml
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#583 fix(nit): delete encoded/unreabable commands in error message
  pkg/docker/client.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
