Repository caicloud/cyclone, pull requests merged in 2018-10, with the labels that each got.

#584 fix: gitlab webhook response body is invalid
  pkg/api/v1/handler/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#585 feature(webhook):pr comment webhook supports display commit statuses
  pkg/api/v1/handler/webhook.go
  pkg/event/manager.go
  pkg/scm/provider/github/github.go
  pkg/scm/provider/gitlab/gitlabv3.go
  pkg/scm/provider/gitlab/gitlabv4.go
  pkg/scm/provider/svn/svn.go
  pkg/scm/scm.go
  pkg/server/manager/project.go
  pkg/util/gitlab/helper.go
Labels: approved, caicloud-cla: yes, lgtm, size/M

#586 fix: alias and description can not be updated to empty
  pkg/server/manager/pipeline.go
  pkg/server/manager/project.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#587 chore(release): update release yaml
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#591 docs(README): add community information
  README.md
  README_zh-CN.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#590 add MIMEText Producer to pipelineRecord Api Descriptor
  pkg/api/v1/descriptor/pipelineRecord.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#593 chore(*): delete Jenkinsfile as unuse
  Jenkinsfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
