Repository caicloud/cyclone, pull requests merged in 2018-03, with the labels that each got.

#364 Cherry pick #331 into release-0.3
  event/event.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#365 fix(#338): add health check for cloud provider
  pkg/server/router/health_check.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#366 feat(server):trigger pipeline by tag
  pkg/scm/provider/github.go
  pkg/scm/provider/gitlab.go
  pkg/scm/scm.go
  pkg/server/manager/project.go
  pkg/server/router/project.go
  pkg/server/router/router.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#363 feat(#361):report real-time build status while the pipelines are running
  pkg/api/types.go
  pkg/event/manager.go
  pkg/server/manager/event.go
  pkg/server/manager/pipelineRecord.go
  pkg/server/router/pipelineRecord.go
  pkg/worker/cycloneserver/client.go
  pkg/worker/scm/manager.go
  pkg/worker/scm/provider/git.go
  pkg/worker/stage/stage.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#370 feat(#356):support context to build image
  pkg/worker/stage/stage.go
Labels: approved, caicloud-cla: yes, lgtm, size/XS

#367 feat(#346): use cache volume to speed up pipeline
  cloud/k8s.go
  cloud/worker.go
  pkg/api/types.go
  pkg/event/manager.go
  pkg/worker/stage/stage.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/L

#374 bug(server):terminate worker after worker exited
  pkg/event/manager.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#371 bug(db):make the member of GenenalStageStatus inline when stored in m…
  pkg/api/types.go
Labels: approved, caicloud-cla: yes, lgtm, size/XS

#372 feat(pipeline):support creating tag when perform pipeline
  pkg/api/types.go
  pkg/scm/provider/github.go
  pkg/scm/provider/gitlab.go
  pkg/scm/scm.go
  pkg/worker/scm/manager.go
  pkg/worker/stage/stage.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#375 feat(pipeline):support to build multiple images
  pkg/worker/stage/stage.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#376 support webhook
  cloud/worker.go
  pkg/api/helper.go
  pkg/api/types.go
  pkg/scm/provider/github.go
  pkg/scm/provider/gitlab.go
  pkg/scm/provider/helper.go
  pkg/scm/scm.go
  pkg/server/manager/pipeline.go
  pkg/server/router/router.go
  pkg/server/router/webhook.go
  pkg/store/pipeline.go
  pkg/util/gitlab/gitlab.go
  pkg/worker/scm/manager.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#381 fix(store): fix error for pipeline
  pkg/store/pipeline.go
Labels: approved, caicloud-cla: yes, release-note-none, size/XS

#382 fix(#373): fix error for integration test
  pkg/docker/client.go
  pkg/worker/stage/stage.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#380 misc(remote): clean up remote manager
  pkg/server/manager/pipeline.go
  remote/interface.go
  remote/manager.go
  remote/manager_test.go
  remote/provider/github.go
  remote/provider/gitlab.go
  remote/provider/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#378 support customized dockerfile
  pkg/worker/stage/stage.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#390 fix(#385): support multiple format for outputs
  pkg/worker/stage/stage.go
Labels: caicloud-cla: yes, release-note-none, size/S

#386 refact(webhook): enhancements and fix error
  pkg/server/router/webhook.go
  pkg/worker/scm/manager.go
  pkg/worker/scm/provider/git.go
  pkg/worker/stage/stage.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#395 refact(worker): use unify Docker client
  pkg/worker/stage/stage.go
Labels: approved, caicloud-cla: yes, lgtm

#398 Remove Go 1.7 and add Go 1.9
  .travis.yml
Labels: approved, caicloud-cla: yes, release-note, size/XS

#392 fix(#352): support registry auth config for projects
  pkg/api/types.go
  pkg/docker/client.go
  pkg/server/manager/project.go
  pkg/worker/stage/stage.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/L

#389 fix(pipeline): support SCM server with ip
  pkg/worker/scm/manager.go
  pkg/worker/scm/manager_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#393 feat(server):support pipeline record status statistics
  pkg/api/types.go
  pkg/server/manager/pipeline.go
  pkg/server/manager/pipeline_test.go
  pkg/server/manager/project.go
  pkg/server/router/pipeline.go
  pkg/server/router/project.go
  pkg/server/router/router.go
  pkg/store/pipelineRecord.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#405 fix(scmgitlab):list all repos from gitlab
  pkg/scm/provider/gitlab.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#408 fix(scmgitlab):list all repos from gitlab (#405)
  pkg/scm/provider/gitlab.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#407 fix(scmgitlab):list all repos from gitlab (#405)
  pkg/scm/provider/gitlab.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
