Repository caicloud/cyclone, pull requests merged in 2018-11, with the labels that each got.

#595 feat(dind) change dind verdion from 17.03.1-ce to 18.03.1-ce
  build/worker/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#598 fix: crd definition problems
  pkg/apis/cyclone/v1alpha1/common.go
  pkg/apis/cyclone/v1alpha1/register.go
  pkg/apis/cyclone/v1alpha1/resource.go
  pkg/apis/cyclone/v1alpha1/stage.go
  pkg/apis/cyclone/v1alpha1/stage_template.go
  pkg/apis/cyclone/v1alpha1/workflow.go
  pkg/apis/cyclone/v1alpha1/workflow_param.go
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/workflow_trigger.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#600 feat(svn): support svn post-commit hook
  build/server/Dockerfile
  docs/api/v1/api.md
  pkg/api/types.go
  pkg/api/v1/descriptor/webhook.go
  pkg/api/v1/handler/webhook.go
  pkg/api/v1/handler/webhook_test.go
  pkg/scm/provider/github/github.go
  pkg/scm/provider/gitlab/gitlabv3.go
  pkg/scm/provider/gitlab/gitlabv4.go
  pkg/scm/provider/svn/svn.go
  pkg/scm/scm.go
  pkg/server/manager/pipeline.go
  pkg/store/pipeline.go
  pkg/util/http/http.go
  pkg/worker/scm/provider/svn.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#602 feat: support trigger pipeline manually by pr
  pkg/api/helper.go
  pkg/api/helper_test.go
  pkg/event/manager.go
  pkg/scm/provider/github/github.go
  pkg/scm/provider/gitlab/gitlab.go
  pkg/scm/provider/gitlab/gitlabv3.go
  pkg/scm/provider/gitlab/gitlabv4.go
  pkg/scm/provider/svn/svn.go
  pkg/scm/scm.go
  pkg/server/manager/pipelineRecord.go
  pkg/util/http/errors/format.go
  pkg/util/regex/regex.go
  pkg/util/regex/regex_test.go
  pkg/worker/scm/manager.go
  pkg/worker/scm/manager_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#596 Resource resolvers
  build/workflow/resolver/git/Dockerfile
  build/workflow/resolver/git/entrypoint.sh
  build/workflow/resolver/image/Dockerfile
  build/workflow/resolver/image/entrypoint.sh
  build/workflow/resolver/kv/Dockerfile
  build/workflow/resolver/kv/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#605 feat(coordinator): add coordinator component
  Makefile
  build/workflow/coordinator/Dockerfile
  cmd/workflow/coordinator/main.go
  pkg/apis/cyclone/v1alpha1/common.go
  pkg/apis/cyclone/v1alpha1/stage_template.go
  pkg/common/constants/constant.go
  pkg/workflow/coordinator/common/types.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/helper.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#611 fix: support update svn hooks
  pkg/api/v1/handler/webhook.go
  pkg/scm/provider/github/github.go
  pkg/scm/provider/gitlab/gitlabv3.go
  pkg/scm/provider/gitlab/gitlabv4.go
  pkg/scm/provider/svn/svn.go
  pkg/scm/scm.go
  pkg/server/manager/pipeline.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#612 refactor and GC
  cmd/workflow/controller/workflow-controller.json
  manifests/config.yaml
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/controllers/workflowrun.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/controller/handlers/workflowrun/dag.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/controller/handlers/workflowrun/operation.go
  pkg/workflow/workflowrun/gc.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/pod.go
  pkg/workflow/workflowrun/timeout.go
  pkg/workflow/workflowrun/timeout_test.go
  pkg/workflow/workflowrun/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#613 fix: update WorkflowTrigger crd
  pkg/apis/cyclone/v1alpha1/workflow_trigger.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#616 feat: turn on cache dependency if pipeline configured it
  pkg/api/v1/handler/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#617 feat: add owner reference to Workflow
  Gopkg.lock
  pkg/apis/cyclone/v1alpha1/workflow_trigger.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/pod.go
  pkg/workflow/workflowrun/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#621 fix: update vendors
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/bench_test.go
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/errors_test.go
  vendor/github.com/pkg/errors/example_test.go
  vendor/github.com/pkg/errors/format_test.go
  vendor/github.com/pkg/errors/stack.go
  vendor/github.com/pkg/errors/stack_test.go
  vendor/github.com/robfig/cron/.gitignore
  vendor/github.com/robfig/cron/.travis.yml
  vendor/github.com/robfig/cron/LICENSE
  vendor/github.com/robfig/cron/README.md
  vendor/github.com/robfig/cron/constantdelay.go
  vendor/github.com/robfig/cron/constantdelay_test.go
  vendor/github.com/robfig/cron/cron.go
  vendor/github.com/robfig/cron/cron_test.go
  vendor/github.com/robfig/cron/doc.go
  vendor/github.com/robfig/cron/parser.go
  vendor/github.com/robfig/cron/parser_test.go
  vendor/github.com/robfig/cron/spec.go
  vendor/github.com/robfig/cron/spec_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#618 PVC GC
  cmd/workflow/controller/workflow-controller.json
  manifests/config.yaml
  pkg/workflow/common/const.go
  pkg/workflow/common/path.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/controllers/workflowrun.go
  pkg/workflow/controller/handlers/pod/gc.go
  pkg/workflow/controller/handlers/pod/handler.go
  pkg/workflow/workflowrun/gc.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/pod.go
  pkg/workflow/workflowrun/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#620 feat: support pvc and path configure in resource
  manifests/examples/ci.yaml
  pkg/apis/cyclone/v1alpha1/resource.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/workflow/common/const.go
  pkg/workflow/common/path.go
  pkg/workflow/workflowrun/pod.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#624 Code improve
  pkg/workflow/controller/controllers/configmap.go
  pkg/workflow/controller/controllers/controller.go
  pkg/workflow/controller/controllers/pod.go
  pkg/workflow/controller/controllers/workflow_trigger.go
  pkg/workflow/controller/controllers/workflowrun.go
  pkg/workflow/controller/handlers/workflowTrigger/handler.go
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#625 chore: adjust default resync period
  pkg/workflow/controller/controllers/configmap.go
  pkg/workflow/controller/controllers/pod.go
  pkg/workflow/controller/controllers/workflow_trigger.go
  pkg/workflow/controller/controllers/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#622 refactor(coordinator): exit immediately when error occurred and check necessity of resources collection
  cmd/workflow/coordinator/main.go
  pkg/workflow/common/event_recorder.go
  pkg/workflow/controller/handlers/workflowtrigger/handler.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
  pkg/workflow/workflowrun/gc.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/timeout.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#626 chore: add travis yaml
  .travis.yml
  pkg/workflow/controller/controllers/pod.go
  pkg/workflow/controller/controllers/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#629 fix: update for deploy issues
  Makefile
  build/workflow/controller/Dockerfile
  manifests/config.yaml
  manifests/cyclone-server.yaml
  manifests/cyclone.yaml
  pkg/workflow/common/const.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/coordinator/helper.go
  pkg/workflow/workflowrun/pod.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#630 fix(server): fix URL for workflowrun and workflowtrigger
  pkg/server/apis/v1alpha1/descriptor/workflowrun.go
  pkg/server/apis/v1alpha1/descriptor/workflowtrigger.go
  pkg/server/apis/v1alpha1/handler/stage.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#632 chore(Makefile): add target 'container-local' for Makefile
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#633 fix: resolve images problems
  build/workflow/resolver/git/entrypoint.sh
  build/workflow/resolver/image/entrypoint.sh
  build/workflow/resolver/kv/entrypoint.sh
  manifests/cyclone.yaml
  manifests/examples/ci.yaml
  manifests/examples/secrets.yaml
  manifests/examples/wfr.yaml
  pkg/apis/cyclone/v1alpha1/resource.go
  pkg/workflow/controller/handlers/pod/handler.go
  pkg/workflow/workflowrun/pod.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#634 fix: inject envs to stage pod
  pkg/workflow/workflowrun/pod.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#614 feat: support code scan with sonarqube
  build/worker/Dockerfile
  docs/api/v1/api.md
  pkg/api/helper.go
  pkg/api/types.go
  pkg/api/v1/descriptor/cloud.go
  pkg/api/v1/descriptor/descriptor.go
  pkg/api/v1/descriptor/integration.go
  pkg/api/v1/handler/handler.go
  pkg/api/v1/handler/integration.go
  pkg/event/manager.go
  pkg/server/manager/integration.go
  pkg/store/integration.go
  pkg/store/store.go
  pkg/util/http/http.go
  pkg/worker/common/constant.go
  pkg/worker/integrate/manager.go
  pkg/worker/integrate/provider/sonar.go
  pkg/worker/scm/manager.go
  pkg/worker/stage/helper.go
  pkg/worker/stage/stage.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL
