Repository caicloud/cyclone, pull requests merged in 2018-08, with the labels that each got.

#545 fix(#544): fix Dockerfile overwritten
  pkg/worker/stage/stage.go
  pkg/worker/stage/stage_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#546 fix:delete related worker pod while deleting pipelineRecord/pipeline/…
  pkg/event/manager.go
  pkg/server/manager/pipelineRecord.go
  pkg/store/event.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#548 fix: retry logic does not work
  pkg/event/manager.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#551 feat(hr): add oauth api for gitlab
  pkg/api/types.go
  pkg/scm/provider/github/github.go
  pkg/scm/provider/gitlab/gitlabv3.go
  pkg/scm/provider/gitlab/gitlabv4.go
  pkg/scm/provider/gitlab/helper.go
  pkg/scm/provider/svn/svn.go
  pkg/scm/scm.go
  pkg/server/router/oauth.go
  pkg/server/router/router.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#552 fix:delete related worker pod failed
  pkg/cloud/kubernetes/kubernetes.go
  pkg/event/manager.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#555 feat(hr): support to skip package stage
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#554 feat: add project name and pipeline name while listing workers
  cmd/worker/options/options.go
  pkg/api/types.go
  pkg/cloud/docker/docker.go
  pkg/cloud/kubernetes/kubernetes.go
  pkg/event/manager.go
  pkg/server/router/cloud.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#547 feat(worker): make package stage optional
  docs/quick-start.md
  docs/quick-start_zh-CN.md
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
