Repository caicloud/cyclone, pull requests merged in 2018-04, with the labels that each got.

#399 Add test case for stage manager
  .travis.yml
  pkg/worker/cycloneserver/fake.go
  pkg/worker/scm/manager.go
  pkg/worker/stage/stage_test.go
Labels: caicloud-cla: yes, release-note-none, size/L

#413 feat(#411): Encrypt password for projects
  api/server/options.go
  api/server/server.go
  cmd/server/options.go
  cmd/server/server.go
  pkg/store/helper.go
  pkg/store/helper_test.go
  pkg/store/project.go
  pkg/store/store.go
  pkg/util/encrypt/encrypt.go
  pkg/util/encrypt/encrypt_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XL

#412 clean up useless code about service
  pkg/store/pipeline.go
  pkg/store/project.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#400 enrich pipeline record infos
  pkg/api/types.go
  pkg/scm/scm.go
  pkg/server/manager/pipeline.go
  pkg/server/router/webhook.go
  pkg/worker/scm/manager.go
  pkg/worker/scm/provider/git.go
  pkg/worker/stage/stage.go
  pkg/worker/stage/stage_test.go
  pkg/worker/worker.go
Labels: caicloud-cla: yes, release-note-none, size/L

#414 refact(store): clean up old store
  api/server/server.go
  pkg/store/store.go
  store/cloud.go
  store/deploy.go
  store/log.go
  store/remote.go
  store/resource.go
  store/service.go
  store/store.go
  store/version.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#418 fix CodeCheckoutStage struct
  pkg/api/types.go
  pkg/server/manager/pipeline.go
  pkg/worker/scm/manager.go
  pkg/worker/stage/stage.go
  pkg/worker/stage/stage_test.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#419 fix:fix bug statistic of pipeline the divisor cannot be 0
  pkg/server/manager/pipeline.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#415 fix(#401): fix glog version
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#420 feat(api): make data inline
  pkg/api/types.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#421 fix:enrich pipeline infon add trigger and owner
  pkg/server/router/pipeline.go
  pkg/server/router/pipelineRecord.go
  pkg/server/router/project.go
  pkg/util/http/http.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#410 fix(#409): Support subtask in image build stage
  pkg/api/types.go
  pkg/server/manager/pipelineRecord.go
  pkg/server/router/pipelineRecord.go
  pkg/server/router/router.go
  pkg/worker/cycloneserver/client.go
  pkg/worker/cycloneserver/fake.go
  pkg/worker/scm/provider/git.go
  pkg/worker/stage/helper.go
  pkg/worker/stage/helper_test.go
  pkg/worker/stage/stage.go
  pkg/worker/stage/stage_test.go
Labels: caicloud-cla: yes, lgtm, release-note-none, size/L

#422 feat(svn):cyclone support svn
  pkg/api/helper.go
  pkg/api/types.go
  pkg/scm/provider/svn.go
  pkg/scm/scm.go
  pkg/store/helper.go
  pkg/worker/scm/manager.go
  pkg/worker/scm/provider/git.go
  pkg/worker/scm/provider/svn.go
  pkg/worker/stage/stage.go
  pkg/worker/stage/stage_test.go
Labels: caicloud-cla: yes, release-note-none, size/L

#427 fix(gitlab):tag is always created based on master for Gitlab
  pkg/scm/provider/github.go
  pkg/scm/provider/gitlab.go
  pkg/scm/provider/svn.go
  pkg/scm/scm.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#424 refact(scm): rename scm type
  Makefile
  pkg/api/helper.go
  pkg/api/types.go
  pkg/scm/provider/github.go
  pkg/scm/provider/gitlab.go
  pkg/scm/scm.go
  pkg/store/helper.go
  pkg/store/helper_test.go
  pkg/worker/scm/manager.go
  pkg/worker/scm/provider/git.go
  pkg/worker/stage/stage_test.go
Labels: caicloud-cla: yes, lgtm, release-note-none, size/L

#428 fix(pipeline):can not delete pipeline
  pkg/server/manager/pipelineRecord.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#429 fix(log): fix log for image release stage
  pkg/worker/stage/stage.go
Labels: caicloud-cla: yes, release-note-none, size/XS

#430 fix(stats):timestamp had an incorrect format
  pkg/api/types.go
  pkg/server/manager/pipeline.go
  pkg/store/pipelineRecord.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none

#433 fix(svn):password is needed when updating project
  pkg/store/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none

#432 chore(*): clean up 0.1 api
  api/templates/yaml/caicloud.yml
  api/types.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#431 fix(log): enhance log stream
  pkg/server/manager/pipelineRecord.go
  pkg/worker/cycloneserver/client.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#434 fix(webhook): fix pipeline record name for webhook trigger
  pkg/server/router/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#435 refact(log): refact the collection of stage logs
  pkg/server/router/pipelineRecord.go
  pkg/store/pipelineRecord.go
  pkg/worker/cycloneserver/client.go
  pkg/worker/stage/helper.go
  pkg/worker/stage/helper_test.go
  pkg/worker/stage/stage.go
  pkg/worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#436 fix(worker):add pipeline record endtime
  pkg/event/manager.go
  pkg/worker/scm/provider/svn.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#447 fix(#446): support filtering multiple fields when list pipeline records
  pkg/util/http/http.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#443 fix(#441): Fail to create Github webhook when create and update pipeline
  pkg/scm/provider/github.go
  pkg/server/manager/pipeline.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#448 fix:change restartPolicy from Always to Never
  cloud/k8s.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#454 fix(#440): delete worker after pipeline finish
  cloud/k8s.go
  cloud/worker.go
  pkg/event/manager.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#455 fix(api):update api
  pkg/api/helper_test.go
  pkg/api/types.go
  pkg/worker/stage/stage.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#457 fix(Makefile):disable cgo of local-build
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#452 fix(pipeline):logs are not display at integration test stage
  pkg/worker/stage/stage.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#456 feat(quota):separate resource request and limit config for worker
  cloud/k8s.go
  cloud/quota.go
  cloud/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#437 feat(stage): support to skip package stage
  api/conversion/conversion.go
  worker/worker.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
