Repository caicloud/cyclone, pull requests merged in 2019-07, with the labels that each got.

#1167 All container logs
  pkg/server/biz/stream/folder.go
  pkg/server/biz/stream/folder_test.go
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1172 fix: sonar qube entrypoint bug fixes
  build/cicd/sonarqube/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1174 chore: add debug logs for sonar qube image
  build/cicd/sonarqube/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1177 perf: improve git resolver performance with --depth
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1173 fix: update wfr with global variable resolved
  pkg/workflow/workflowrun/operator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1181 fix: add auth info when get scan results
  build/cicd/sonarqube/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1179 chore: add supported kubernetes versions
  README.md
  docs/installation.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1187 fix: low level bug of gitlab v3 version
  pkg/server/biz/scm/gitlab/gitlabv3.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1191 chore: disable PVC watcher
  pkg/server/biz/integration/cluster/cluster.go
  pkg/server/biz/pvc/pvc.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1193 fix(error code): clarify error code
  pkg/server/biz/hook/scm.go
  pkg/server/biz/integration/sonarqube/sonarqube.go
  pkg/server/biz/scm/bitbucket/server/server.go
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/biz/scm/scm.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1195 fix: skip ssl verify for gitlab
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1194 fix(bitbucket): need response to do error check
  pkg/server/biz/scm/bitbucket/server/v1Client.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1197 fix(git-resolver): can not pull bitbucket code with personal access token
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1198 fix: label value for wft event repo too long
  pkg/server/biz/hook/scm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1199 feat(server): support dry-run for creating integration
  pkg/server/apis/v1alpha1/descriptors/integration.go
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/util/http/http.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1200 fix: make dind bip configurable
  helm/cyclone/templates/controller.yaml
  helm/cyclone/values.yaml
  pkg/workflow/controller/config.go
  pkg/workflow/workload/pod/builder.go
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1201 fix: github release event webhook trigger workflow twice
  pkg/server/biz/scm/github/github.go
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1203 feat: make resource requirement of gc pod configurable
  helm/cyclone/templates/controller.yaml
  helm/cyclone/values.yaml
  pkg/workflow/controller/config.go
  pkg/workflow/workflowrun/operator.go
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1204 chore: update gradle image version to 5.5.1 for stage template
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/unit-test.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1205 feat(api): support list pull requests of scm repo
  pkg/server/apis/v1alpha1/descriptors/integration.go
  pkg/server/biz/scm/bitbucket/server/repos.go
  pkg/server/biz/scm/bitbucket/server/server.go
  pkg/server/biz/scm/bitbucket/server/v1Client.go
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/biz/scm/scm.go
  pkg/server/biz/scm/svn/svn.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1208 fix: can not list working pods
  pkg/server/handler/v1alpha1/workload.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1209 feat(oauth): cherry-pick from v0.9.5 to v0.9.7-alpha
  README.md
  build/cicd/sonarqube/entrypoint.sh
  build/resolver/git/entrypoint.sh
  docs/installation.md
  pkg/server/biz/integration/cluster/cluster.go
  pkg/server/biz/pvc/pvc.go
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/stream/folder.go
  pkg/server/biz/stream/folder_test.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/util/retry/retry.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/workload.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL
