Repository caicloud/cyclone, pull requests merged in 2019-05, with the labels that each got.

#950 fix: unescape cmd argument
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/code-scan.yaml
  manifests/templates/cicd/image-build.yaml
  manifests/templates/cicd/unit-test.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#952 fix: average resource requirements to every container
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#954 feat: support bitbucket server in scm
  cmd/server/main.go
  pkg/server/apis/v1alpha1/types.go
  pkg/server/biz/scm/bitbucket/bitbucket-server/auths.go
  pkg/server/biz/scm/bitbucket/bitbucket-server/bitbucket_server.go
  pkg/server/biz/scm/bitbucket/bitbucket-server/pull_requests.go
  pkg/server/biz/scm/bitbucket/bitbucket-server/repos.go
  pkg/server/biz/scm/bitbucket/bitbucket-server/repos_webhooks.go
  pkg/server/biz/scm/bitbucket/bitbucket-server/v1Client.go
  pkg/server/biz/scm/bitbucket/bitbucket-server/webhooks.go
  pkg/server/biz/scm/bitbucket/bitbucket.go
  pkg/server/biz/scm/scm.go
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#955 fix: svn revision
  build/resolver/svn/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#953 fix: fix panic nil-pointer dereference
  pkg/server/handler/v1alpha1/notification.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#945 feat: use helm chart to deploy
  helm/cyclone/.helmignore
  helm/cyclone/Chart.yaml
  helm/cyclone/templates/_helpers.tpl
  helm/cyclone/templates/controller.yaml
  helm/cyclone/templates/crd.yaml
  helm/cyclone/templates/server.yaml
  helm/cyclone/templates/service-account.yaml
  helm/cyclone/templates/web.yaml
  helm/cyclone/values.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#956 improve: make open control cluster configurable
  manifests/cyclone.yaml.template
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/tenant.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#961 fix: disable css module for antd
  web/config/webpack.config.prod.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#964 fix: allow svn revision to be empty
  build/resolver/svn/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#962 chore: update favicon with cyclone logo
  web/public/favicon.ico
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#963 fix: add cyclone logo to web header
  web/src/images/logo.png
  web/src/layout/index.js
  web/src/less/inc.var.less
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#968 feat: change locale in web
  web/src/layout/index.js
  web/src/less/inc.var.less
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#960 feat(devops): avoid stage forming closed loop dependence
  web/src/api/index.js
  web/src/components/project/component/detail/index.js
  web/src/components/public/makeField/select.js
  web/src/components/workflow/component/add/BasicInfo.js
  web/src/components/workflow/component/add/CreateWorkflow.js
  web/src/components/workflow/component/add/Form.js
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/list/ListLayout.js
  web/src/components/workflow/component/list/WorkflowTable.js
  web/src/components/workflow/component/list/index.js
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/SCM.js
  web/src/components/workflow/component/stage/StageField.js
  web/src/components/workflow/index.js
  web/src/lib/const.js
  web/src/store/index.js
  web/src/store/project.js
  web/src/store/resource.js
  web/src/store/workflow.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#965 docs: add cii best practices
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#969 feat(devops): submit workflow form data
  web/src/components/workflow/component/add/CreateWorkflow.js
  web/src/components/workflow/component/add/Form.js
  web/src/components/workflow/component/list/ListLayout.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#928 feat(web): detail-page for template & create template
  web/src/api/index.js
  web/src/components/stageTemplate/Detail/Configuration.js
  web/src/components/stageTemplate/Detail/Inputs.js
  web/src/components/stageTemplate/Detail/Outputs.js
  web/src/components/stageTemplate/Detail/detail.module.less
  web/src/components/stageTemplate/Detail/index.js
  web/src/components/stageTemplate/List/Item.js
  web/src/components/stageTemplate/List/index.js
  web/src/components/stageTemplate/add/Config.js
  web/src/components/stageTemplate/add/Form.js
  web/src/components/stageTemplate/add/FormContent.js
  web/src/components/stageTemplate/add/Input.js
  web/src/components/stageTemplate/add/Output.js
  web/src/components/stageTemplate/add/SelectSourceType.js
  web/src/components/stageTemplate/add/index.js
  web/src/components/stageTemplate/add/template.module.less
  web/src/components/stageTemplate/add/validate.js
  web/src/components/stageTemplate/index.js
  web/src/lib/const.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/stageTemplate.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#975 fix: scm push event trigger does not work
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#967 fix: tag does not take effect when there is a default value
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#971 refact: refact label value
  pkg/meta/labels.go
  pkg/meta/labels_test.go
  pkg/server/biz/accelerator/accelerate.go
  pkg/server/biz/accelerator/accelerate_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#958 chore: update docs for helm chart install
  Makefile
  README.md
  docs/installation.md
  helm/cyclone/templates/controller.yaml
  helm/cyclone/templates/server.yaml
  helm/cyclone/values.yaml
  pkg/workflow/workflowrun/execution_context.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#977 fix: default cluster when empty in execution context
  pkg/workflow/common/cluster.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#976 change close cluster logic
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/tenant.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#970 feat: implement integration detail page
  web/src/components/integration/component/detail/index.js
  web/src/less/u.detail.less
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#972 fix(templateKind): fix undefined template kind present null item
  web/src/components/stageTemplate/List/index.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#982 chore: ui styles in template
  web/src/components/stageTemplate/Detail/index.js
  web/src/components/stageTemplate/List/Item.js
  web/src/components/stageTemplate/List/list.module.less
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#984 fix: ExecutionCluter creation before CRD
  cmd/workflow/controller/main.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#983 feat(workflow): workflow detail page and template stage
  web/src/api/index.js
  web/src/components/workflow/component/add/CreateWorkflow.js
  web/src/components/workflow/component/add/Form.js
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/detail/StageDepend.js
  web/src/components/workflow/component/detail/WorkflowDetail.js
  web/src/components/workflow/component/detail/index.js
  web/src/components/workflow/component/list/ListLayout.js
  web/src/components/workflow/component/list/WorkflowTable.js
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/components/workflow/component/resource/SCM.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/StageField.js
  web/src/components/workflow/component/stage/TemplateStage.js
  web/src/components/workflow/index.js
  web/src/lib/const.js
  web/src/lib/util.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/workflow.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#985 chore(stageTemplate): modify stageTemplate logic with resource type
  web/src/components/stageTemplate/List/Item.js
  web/src/components/stageTemplate/List/index.js
  web/src/components/stageTemplate/List/list.module.less
  web/src/components/stageTemplate/add/Form.js
  web/src/components/stageTemplate/add/FormContent.js
  web/src/components/stageTemplate/add/Input.js
  web/src/components/stageTemplate/add/Output.js
  web/src/components/stageTemplate/add/ResourceType.js
  web/src/components/stageTemplate/add/SelectSourceType.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#986 feat: support multiple workflow controller
  pkg/common/const.go
  pkg/meta/labels.go
  pkg/workflow/controller/controllers/workflow_trigger.go
  pkg/workflow/controller/controllers/workflowrun.go
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#989 fix(stageTemplate): fix update template url
  web/src/components/stageTemplate/List/Item.js
  web/src/components/stageTemplate/index.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#981 fix(#979): fix namespace when installed by helm
  README.md
  build/workflow/controller/Dockerfile
  cmd/server/main.go
  cmd/workflow/controller/main.go
  docs/installation.md
  helm/cyclone/templates/controller.yaml
  helm/cyclone/templates/server.yaml
  helm/cyclone/templates/web.yaml
  helm/cyclone/values.yaml
  pkg/common/const.go
  pkg/server/common/const.go
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/template.go
  pkg/workflow/common/const.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#957 docs: explain the limitation of supported external systems
  docs/design.md
  docs/user_guide.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#988 feat: collect stage result to wfr status
  Makefile
  build/resolver/kv/Dockerfile
  build/resolver/kv/entrypoint.sh
  cmd/workflow/coordinator/main.go
  docs/stage-execution-result.md
  helm/cyclone/templates/service-account.yaml
  pkg/apis/cyclone/v1alpha1/resource.go
  pkg/meta/annotations.go
  pkg/workflow/common/const.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#990 feat(stageTemplate): add a verification method to the resource select form item
  web/src/components/stageTemplate/add/Input.js
  web/src/components/stageTemplate/add/Output.js
  web/src/components/stageTemplate/add/ResourceType.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#993 fix: update label when open/close cluster
  pkg/server/handler/v1alpha1/integration.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#991 feat: create service account when open cluster
  pkg/server/biz/integration/cluster/cluster.go
  pkg/server/biz/integration/cluster/service_account.go
  pkg/server/biz/integration/converter.go
  pkg/server/biz/integration/name.go
  pkg/server/biz/tenant/tenant.go
  pkg/server/biz/utils/collection.go
  pkg/server/common/utils.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/stage.go
  pkg/server/handler/v1alpha1/storage.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
  pkg/server/handler/v1alpha1/workload.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#995 feat: add cyclone official website for refs
  web/src/layout/index.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#996 fix: ignore not found error while delete pvc watcher
  pkg/server/biz/pvc/pvc.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#997 fix: skip git ssl verify
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#994 [Web] feat: open/close cluster in integration center
  web/src/api/index.js
  web/src/components/integration/component/detail/index.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/integration.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1005 feat(api): support operate public integration
  pkg/server/apis/v1alpha1/descriptors/integration.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/notification.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/util/http/http.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1001 chore(stageTemplate): remove template item hover style
  web/src/components/stageTemplate/List/Item.js
  web/src/components/stageTemplate/List/list.module.less
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1002 chore(stageTemplate): remove resources type validation
  web/src/components/stageTemplate/add/Input.js
  web/src/components/stageTemplate/add/Output.js
  web/src/components/stageTemplate/add/validate.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1004 chore(templateDetail): remove entrypoint & modify cmd display value
  web/src/components/stageTemplate/Detail/Configuration.js
  web/src/components/stageTemplate/add/Form.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1003 chore(stageTemplate): replace cmd component with textarea & modify style
  web/src/components/stageTemplate/add/Config.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1000 feat: add SonarQube image and stage template
  Makefile
  build/cicd/sonarqube/Dockerfile
  build/cicd/sonarqube/entrypoint.sh
  manifests/templates/cicd/sonarqube.yaml
  pkg/workflow/workflowrun/operator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1006 feat(api): support filter integrations
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#999 Replace metalinter with golangci-lint
  .gometalinter.json
  .travis.yml
  Makefile
  pkg/meta/labels.go
  pkg/server/apis/v1alpha1/descriptors/workflow.go
  pkg/server/biz/accelerator/accelerate_test.go
  pkg/server/biz/integration/converter.go
  pkg/server/biz/scm/bitbucket/bitbucket.go
  pkg/server/biz/scm/bitbucket/server/auths.go
  pkg/server/biz/scm/bitbucket/server/bitbucket_server.go
  pkg/server/biz/scm/bitbucket/server/pull_requests.go
  pkg/server/biz/scm/bitbucket/server/repos.go
  pkg/server/biz/scm/bitbucket/server/repos_webhooks.go
  pkg/server/biz/scm/bitbucket/server/v1Client.go
  pkg/server/biz/scm/bitbucket/server/webhooks.go
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/biz/templates/stages.go
  pkg/server/common/cluster.go
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
  pkg/util/context/context.go
  pkg/util/slugify/slugify_test.go
  pkg/workflow/common/selector.go
  pkg/workflow/controller/handlers/configmap/handler.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/cycloneserver/client.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
  pkg/workflow/workflowrun/gc_test.go
  pkg/workflow/workflowrun/limits.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/timeout.go
  pkg/workflow/workflowrun/timeout_test.go
  pkg/workflow/workload/pod/secret.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1007 feat: validate token while creating sonarqube integration
  pkg/meta/labels.go
  pkg/server/biz/integration/sonarqube/sonarqube.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#992 feat(update): update workflow
  web/src/api/http.js
  web/src/api/index.js
  web/src/components/workflow/component/add/CreateWorkflow.js
  web/src/components/workflow/component/add/Form.js
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/add/util.js
  web/src/components/workflow/component/detail/StageDepend.js
  web/src/components/workflow/component/detail/WorkflowDetail.js
  web/src/components/workflow/component/list/WorkflowTable.js
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/StageField.js
  web/src/components/workflow/component/stage/TemplateStage.js
  web/src/components/workflow/index.js
  web/src/lib/util.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/resource.js
  web/src/store/workflow.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#1009 fix(release): fix report url for storage watcher
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1014 feat: get last commit id in git resolver
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1015 feat: support collect execution results from init-container
  pkg/workflow/coordinator/coordinator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1012 feat(devops): run workflow
  web/src/api/http.js
  web/src/api/index.js
  web/src/components/integration/component/MenuAction.js
  web/src/components/project/component/MenuAction.js
  web/src/components/public/makeField/select.js
  web/src/components/workflow/component/MenuAction.js
  web/src/components/workflow/component/RunWorkflow.js
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/detail/WorkflowDetail.js
  web/src/components/workflow/component/detail/WorkflowRuns.js
  web/src/components/workflow/component/list/WorkflowTable.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/SCM.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/resource.js
  web/src/store/workflow.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#1008 fix(stageTemplate): fix array input blur with dynamic field key
  web/src/components/stageTemplate/add/Config.js
  web/src/components/stageTemplate/add/Output.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1021 fix: list workflow triggers belonged to the specific workflow
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1026 chore(style): adjust quta style disorder
  web/src/less/u.resourceAllocation.less
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1017 feat: support generation type values in argument
  pkg/common/values/generators.go
  pkg/common/values/generators_test.go
  pkg/common/values/nowtime.go
  pkg/common/values/nowtime_test.go
  pkg/common/values/random.go
  pkg/common/values/random_test.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1019 docs: update user guide and design docs
  docs/design.md
  docs/user_guide.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1027 fix(git-resolver): encode token string
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1018 chore: add slack invitation link
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1025 refactor: scm webhook trigger
  pkg/meta/labels.go
  pkg/server/apis/v1alpha1/descriptors/webhook.go
  pkg/server/biz/hook/hook.go
  pkg/server/biz/hook/scm.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#1020 fix: Fix error and enhance tag in makefile
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1016 feat: add apis to list dockerfiles from scm
  pkg/server/apis/v1alpha1/descriptors/integration.go
  pkg/server/biz/scm/bitbucket/server/bitbucket_server.go
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/biz/scm/helper.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1031 fix: list templates/integration for default template
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/template.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1030 fix: update helm charts for serviceaccount
  helm/cyclone/Chart.yaml
  helm/cyclone/templates/controller.yaml
  helm/cyclone/templates/server.yaml
  helm/cyclone/templates/service-account.yaml
  helm/cyclone/templates/web.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1032 fix: can not update svn type integration
  pkg/server/biz/scm/scm.go
  pkg/server/handler/v1alpha1/integration.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1033 chore: clean makefile
  Makefile
  manifests/crd.yaml
  manifests/cyclone.yaml.template
  manifests/generate.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1036 fix: cyclone.io to cyclone.dev
  web/src/components/stageTemplate/Detail/index.js
  web/src/components/stageTemplate/List/Item.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1035 feat: add description to arguments
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/cd.yaml
  manifests/templates/cicd/code-scan.yaml
  manifests/templates/cicd/image-build.yaml
  manifests/templates/cicd/sonarqube.yaml
  manifests/templates/cicd/unit-test.yaml
  pkg/apis/cyclone/v1alpha1/common.go
  web/src/components/stageTemplate/Detail/Inputs.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1028 chore: update readme for cycli
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1037 remove-resource-name
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/image-build.yaml
  manifests/templates/cicd/sonarqube.yaml
  manifests/templates/cicd/unit-test.yaml
  web/src/components/stageTemplate/Detail/Inputs.js
  web/src/components/stageTemplate/Detail/Outputs.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1038 chore: get webhook url from env
  helm/cyclone/templates/server.yaml
  helm/cyclone/values.yaml
  pkg/server/biz/hook/scm.go
  pkg/server/config/config.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1039 feat(resource): resource type select
  web/src/components/workflow/component/resource/BindResource.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1040 feat: support svn post commit hook
  pkg/apis/cyclone/v1alpha1/workflow_trigger.go
  pkg/server/biz/hook/scm.go
  pkg/server/biz/scm/scm.go
  pkg/server/biz/scm/svn/svn.go
  pkg/server/common/const.go
  pkg/server/handler/v1alpha1/webhook.go
Labels: caicloud-cla: yes, release-note-none, size/L

#1034 chore(stageTemplate): fix template form error with field arguments & cmd
  web/src/components/public/makeField/autoComplete.js
  web/src/components/stageTemplate/List/index.js
  web/src/components/stageTemplate/add/Config.js
  web/src/components/stageTemplate/add/Form.js
  web/src/components/stageTemplate/add/FormContent.js
  web/src/components/stageTemplate/add/Input.js
  web/src/components/stageTemplate/add/validate.js
  web/src/lib/const.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1045 feat(workflow): add field level validate
  web/src/api/http.js
  web/src/components/workflow/component/add/BasicInfo.js
  web/src/components/workflow/component/add/CreateWorkflow.js
  web/src/components/workflow/component/add/Form.js
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/SCM.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/StageField.js
  web/src/components/workflow/component/stage/TemplateStage.js
  web/src/lib/const.js
  web/src/lib/util.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1046 fix(project): remove integration selelct in add project
  web/src/components/project/component/addProject/FormContent.js
  web/src/components/project/component/addProject/FormWrap.js
  web/src/components/project/component/addProject/IntegrationSelect.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1043 fix: highlight cmd in template detail page
  manifests/templates/cicd/unit-test.yaml
  web/package.json
  web/src/components/stageTemplate/Detail/Inputs.js
  web/src/components/stageTemplate/Detail/index.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1048 fix(stageTemplate): fix configuration cmd value & resource options
  web/src/components/stageTemplate/Detail/Configuration.js
  web/src/components/stageTemplate/Detail/Inputs.js
  web/src/components/stageTemplate/List/Item.js
  web/src/components/stageTemplate/List/list.module.less
  web/src/components/stageTemplate/add/Form.js
  web/src/components/stageTemplate/add/Input.js
  web/src/components/stageTemplate/add/Output.js
  web/src/components/stageTemplate/add/ResourceType.js
  web/src/components/stageTemplate/add/SelectSourceType.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1049 fix: integration center problems in web
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/handler/v1alpha1/integration.go
  web/src/components/integration/component/createIntegration/FormWrap.js
  web/src/components/integration/component/formGroup/DockerRegistry/index.js
  web/src/components/integration/component/formGroup/ScmGroup/Forms/AuthSelector.js
  web/src/components/stageTemplate/Detail/Inputs.js
  web/src/components/stageTemplate/Detail/detail.module.less
  web/src/consts/const.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: caicloud-cla: yes, lgtm, release-note-none, size/M

#1042 fix: create cron type trigger failed
  pkg/server/biz/hook/hook.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
Labels: approved, caicloud-cla: yes, lgtm, size/M

#1051 fix: cyclone web problems
  web/src/components/project/component/detail/index.js
  web/src/components/public/makeField/select.js
  web/src/components/stageTemplate/Detail/Inputs.js
  web/src/components/stageTemplate/Detail/detail.module.less
  web/src/components/workflow/component/MenuAction.js
  web/src/components/workflow/component/RunWorkflow.js
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/list/ListLayout.js
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/StageField.js
  web/src/components/workflow/component/stage/TemplateStage.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1052 fix(devops): validate resource field array
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1044 docs: add svn post commit hook user guide
  docs/user_guide.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1054 chore(stageTemplate): support resourceTypes select api
  web/src/api/index.js
  web/src/components/stageTemplate/add/FormContent.js
  web/src/components/stageTemplate/add/Input.js
  web/src/components/stageTemplate/add/Output.js
  web/src/store/resource.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1053 fix(workflow): modify stage template select options key & alias
  web/src/components/workflow/component/stage/AddStage.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1055 fix(stage): The verification method is incorrectly used.
  web/src/components/workflow/component/add/CreateWorkflow.js
  web/src/components/workflow/component/add/Form.js
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/index.module.less
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/TemplateStage.js
  web/src/lib/const.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1056 feat: manage resource type apis
  helm/cyclone/templates/resource-type.yaml
  pkg/apis/cyclone/v1alpha1/resource.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/meta/labels.go
  pkg/server/apis/v1alpha1/descriptors/resourcetypes.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/resourcetypes.go
  pkg/util/http/http.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1057 fix(graph): fix intl problem
  web/src/components/workflow/component/add/Graph.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1050 fix: make coordinator exit gracefully
  cmd/workflow/coordinator/main.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1058 fix(devops): get resource arguments from api
  web/src/api/http.js
  web/src/api/index.js
  web/src/components/public/makeField/Field.js
  web/src/components/workflow/component/add/util.js
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/components/workflow/component/resource/SCM.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/lib/const.js
  web/src/store/resource.js
  web/yarn.lock
Labels: caicloud-cla: yes, lgtm, release-note-none, size/XL

#1062 fix(#1059): list all branches and tags from scm repo
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/biz/scm/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1060 chore(workflow): drawer show close button
  web/src/components/workflow/component/add/Graph.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1061 chore(stageTemplate): add dirty to form & disable submit button
  web/src/components/integration/component/createIntegration/FormContent.js
  web/src/components/stageTemplate/add/Form.js
  web/src/components/stageTemplate/add/FormContent.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1063 feat: manage resource types
  helm/cyclone/templates/resource-type.yaml
  pkg/apis/cyclone/v1alpha1/common.go
  pkg/server/apis/v1alpha1/descriptors/resourcetypes.go
  pkg/server/handler/v1alpha1/resourcetypes.go
  web/src/api/index.js
  web/src/components/resource/component/List.js
  web/src/components/resource/component/MenuAction.js
  web/src/components/resource/component/create/FormContent.js
  web/src/components/resource/component/create/index.js
  web/src/components/resource/component/detail/index.js
  web/src/components/resource/index.js
  web/src/components/stageTemplate/add/Input.js
  web/src/layout/index.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/routes/index.js
  web/src/store/resource.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#1064 feat(workflow): stage resource missing name
  web/src/components/workflow/component/add/util.js
  web/src/components/workflow/component/detail/WorkflowRuns.js
  web/src/components/workflow/component/index.module.less
  web/src/components/workflow/component/list/WorkflowTable.js
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/TemplateStage.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/resource.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1065 fix(resourceTypes): fix resource type parameters switch defaultvalue
  web/src/components/resource/component/create/FormContent.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1066 fix: avoid istio sidecar injection
  pkg/meta/annotations.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1067 fix(stage): stage store useless for stageDetail
  web/src/components/public/ellipsisMenu/index.js
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/add/util.js
  web/src/components/workflow/component/detail/WorkflowDetail.js
  web/src/components/workflow/component/index.module.less
  web/src/components/workflow/component/list/WorkflowTable.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/StageField.js
  web/src/store/resource.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1068 fix: resolve args for coordinator
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
