Repository caicloud/cyclone, pull requests merged in 2019-02, with the labels that each got.

#781 fix: update label when change integration type
  pkg/server/handler/v1alpha1/integration.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#772 feat(integrationCenter): modify submit logic & add update integration
  web/src/api/index.js
  web/src/components/integration/component/List.js
  web/src/components/integration/component/MenuAction.js
  web/src/components/integration/component/createIntegration/FormContent.js
  web/src/components/integration/component/createIntegration/FormWrap.js
  web/src/components/integration/component/createIntegration/SelectSourceType.js
  web/src/components/integration/component/createIntegration/index.js
  web/src/components/integration/component/detail/index.js
  web/src/components/integration/component/formGroup/DockerRegistry/index.js
  web/src/components/integration/component/formGroup/ScmGroup/Forms/GitHub.js
  web/src/components/integration/component/formGroup/ScmGroup/Forms/GitLab.js
  web/src/components/integration/component/formGroup/ScmGroup/Forms/ValidateSelect.js
  web/src/components/integration/component/formGroup/ScmGroup/Selection.js
  web/src/components/integration/component/formGroup/ScmGroup/index.js
  web/src/components/integration/component/formGroup/SonarQube/index.js
  web/src/components/integration/index.js
  web/src/less/u.integrationCenter.less
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/integration.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#784 feat(integrationCenter): mv validate from form wrap to out side
  web/src/components/integration/component/createIntegration/FormWrap.js
  web/src/components/integration/component/createIntegration/validate.js
  web/src/store/integration.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#782 feat(web): add component to display K-V
  web/src/components/public/KeyValue/README.md
  web/src/components/public/KeyValue/index.js
  web/src/components/public/KeyValue/keyValue.module.less
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#785 chore: add description and alias for default tenant and cluster
  pkg/server/handler/v1alpha1/tenant.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#787 refactor(server): configure cyclone server by configmap
  cmd/server/main.go
  manifests/cyclone.yaml.template
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/tenant.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#788 fix: use default value of pvc size and resource quota if they are empty
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/tenant.go
Labels: approved, caicloud-cla: yes, release-note-none, size/S

#793 docs(design): add functional modules
  docs/design.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#786 chore(integrationCenter):modify integration data source type key
  web/src/components/integration/component/createIntegration/FormContent.js
  web/src/components/integration/component/createIntegration/FormWrap.js
  web/src/components/integration/component/createIntegration/SelectSourceType.js
  web/src/components/integration/component/createIntegration/validate.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#790 fix: return success if ns,quota,pvc exist while open worker cluster
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#796 fix: fix default pvc size unit
  manifests/cyclone.yaml.template
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#798 fix: return code should be 409 while creating resource conflict
  pkg/server/handler/v1alpha1/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#799 add arg -w0 to base64, fix make deploy error
  manifests/generate.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#800 chore: add authType field in SCMSource
  pkg/server/apis/v1alpha1/types.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#803 fix(server): can not get built in stage template
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/code-scan.yaml
  manifests/templates/cicd/image-build.yaml
  manifests/templates/cicd/unit-test.yaml
  pkg/server/apis/v1alpha1/descriptors/template.go
  pkg/server/common/const.go
  pkg/server/common/utils.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/template.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
