Repository caicloud/cyclone, pull requests merged in 2019-01, with the labels that each got.

#695 fix: fix bug of release chart
  release/cyclone-server.yaml
  release/workflow-controller.yaml
Labels: caicloud-cla: yes, release-note-none, size/S

#700 fix(trigger): reduce the name length of wfr created by trigger
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: approved, caicloud-cla: yes, size/S

#701 fix(trigger): break on success or failed
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: caicloud-cla: yes, lgtm, release-note-none, size/XS

#702 fix(trigger): fix import error
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: caicloud-cla: yes, lgtm, release-note-none, size/XS

#688 feat(*): sideNav add collapsible prop and detail component add action
  web/src/components/project/component/ProjectDetail.js
  web/src/components/public/detail/Action.js
  web/src/components/public/detail/index.js
  web/src/components/public/detail/index.md
  web/src/layout/index.js
  web/src/less/inc.var.less
  web/src/less/index.less
  web/src/less/u-detail.less
Labels: caicloud-cla: yes, lgtm, release-note-none, size/M

#683 feat(integrationCenter): add integration center module
  web/src/components/integration/component/DataForm.js
  web/src/components/integration/component/List.js
  web/src/components/integration/index.js
  web/src/layout/index.js
  web/src/locale/en-US.json
  web/src/locale/zh-CN.json
  web/src/routes/index.js
  web/src/store/index.js
  web/src/store/integration.js
Labels: caicloud-cla: yes, release-note-none, size/L

#697 chore: update README
  CONTRIBUTING.md
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#711 fix(inteigrationCenter): fix bug for removing ref Deprecated feature
  web/src/components/integration/component/List.js
  web/src/locale/en-US.json
  web/src/locale/zh-CN.json
Labels: caicloud-cla: yes, lgtm, release-note-none, size/S

#714 fix: workflowrun limits problem
  pkg/common/constant.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/workflowrun/limits.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#716 fix: update api group
  pkg/apis/cyclone/v1alpha1/doc.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cyclone/v1alpha1/zz_generated.defaults.go
  pkg/k8s/clientset/clientset.go
  pkg/k8s/clientset/doc.go
  pkg/k8s/clientset/fake/clientset_generated.go
  pkg/k8s/clientset/fake/doc.go
  pkg/k8s/clientset/fake/register.go
  pkg/k8s/clientset/scheme/doc.go
  pkg/k8s/clientset/scheme/register.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/cyclone_client.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/doc.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/doc.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_cyclone_client.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_resource.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_stage.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_stagetemplate.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_workflow.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_workflowparam.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_workflowrun.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_workflowtrigger.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/generated_expansion.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/resource.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/stage.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/stagetemplate.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/workflow.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/workflowparam.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/workflowrun.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/workflowtrigger.go
  pkg/k8s/informers/cyclone/interface.go
  pkg/k8s/informers/cyclone/v1alpha1/interface.go
  pkg/k8s/informers/cyclone/v1alpha1/resource.go
  pkg/k8s/informers/cyclone/v1alpha1/stage.go
  pkg/k8s/informers/cyclone/v1alpha1/stagetemplate.go
  pkg/k8s/informers/cyclone/v1alpha1/workflow.go
  pkg/k8s/informers/cyclone/v1alpha1/workflowparam.go
  pkg/k8s/informers/cyclone/v1alpha1/workflowrun.go
  pkg/k8s/informers/cyclone/v1alpha1/workflowtrigger.go
  pkg/k8s/informers/factory.go
  pkg/k8s/informers/generic.go
  pkg/k8s/listers/cyclone/v1alpha1/expansion_generated.go
  pkg/k8s/listers/cyclone/v1alpha1/resource.go
  pkg/k8s/listers/cyclone/v1alpha1/stage.go
  pkg/k8s/listers/cyclone/v1alpha1/stagetemplate.go
  pkg/k8s/listers/cyclone/v1alpha1/workflow.go
  pkg/k8s/listers/cyclone/v1alpha1/workflowparam.go
  pkg/k8s/listers/cyclone/v1alpha1/workflowrun.go
  pkg/k8s/listers/cyclone/v1alpha1/workflowtrigger.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#715 quick build and deploy
  Makefile
  build/resolver/git/Dockerfile
  build/resolver/git/entrypoint.sh
  build/resolver/image/Dockerfile
  build/resolver/image/entrypoint.sh
  build/resolver/kv/Dockerfile
  build/resolver/kv/entrypoint.sh
  build/web/Dockerfile
  build/web/Dockerfile.local
  build/web/Dockerfile.multistage
  build/web/nginx.conf
  manifests/cyclone.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#724 feat(oauth):support oauth way to create project
  pkg/api/types.go
  pkg/api/v1/descriptor/oauth.go
  pkg/api/v1/handler/oauth.go
  pkg/util/http/http.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#722 chore: go code checker in travis
  .gometalinter.json
  .travis.yml
  Makefile
  cmd/workflow/coordinator/main.go
  pkg/apis/cyclone/v1alpha1/crd.go
  pkg/apis/cyclone/v1alpha1/doc.go
  pkg/apis/cyclone/v1alpha1/register.go
  pkg/apis/cyclone/v1alpha1/resource.go
  pkg/apis/cyclone/v1alpha1/stage.go
  pkg/apis/cyclone/v1alpha1/stage_template.go
  pkg/apis/cyclone/v1alpha1/workflow.go
  pkg/apis/cyclone/v1alpha1/workflow_param.go
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/workflow_trigger.go
  pkg/common/client.go
  pkg/server/apis/v1alpha1/descriptors/resource.go
  pkg/server/config/config.go
  pkg/server/handler/resource.go
  pkg/server/handler/stage.go
  pkg/server/handler/workflow.go
  pkg/server/handler/workflowrun.go
  pkg/server/handler/workflowtrigger.go
  pkg/util/cerr/error.go
  pkg/util/context/context.go
  pkg/util/file/file.go
  pkg/util/file/file_test.go
  pkg/util/http/http.go
  pkg/util/websocket/websocket.go
  pkg/workflow/common/const.go
  pkg/workflow/common/event_recorder.go
  pkg/workflow/common/path.go
  pkg/workflow/common/selector.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/controllers/configmap.go
  pkg/workflow/controller/controllers/controller.go
  pkg/workflow/controller/controllers/pod.go
  pkg/workflow/controller/controllers/workflow_trigger.go
  pkg/workflow/controller/controllers/workflowrun.go
  pkg/workflow/controller/handlers/configmap/handler.go
  pkg/workflow/controller/handlers/interface.go
  pkg/workflow/controller/handlers/pod/handler.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
  pkg/workflow/controller/handlers/workflowtrigger/handler.go
  pkg/workflow/controller/init.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/cycloneserver/client.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
  pkg/workflow/workflowrun/gc.go
  pkg/workflow/workflowrun/gc_test.go
  pkg/workflow/workflowrun/limits.go
  pkg/workflow/workflowrun/limits_test.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/operator_test.go
  pkg/workflow/workflowrun/pod.go
  pkg/workflow/workflowrun/timeout.go
  pkg/workflow/workflowrun/timeout_test.go
  pkg/workflow/workflowrun/utils.go
  pkg/workflow/workflowrun/utils_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#718 feat(stage): list of inner stage-template
  web/config/webpack.config.dev.js
  web/config/webpack.config.prod.js
  web/mock/stageTemplate.js
  web/public/index.html
  web/src/api/index.js
  web/src/components/project/component/ProjectDetail.js
  web/src/components/public/detail/index.md
  web/src/components/public/ellipsisMenu/index.md
  web/src/components/stageTemplate/List/Item.js
  web/src/components/stageTemplate/List/List.js
  web/src/components/stageTemplate/List/index.js
  web/src/components/stageTemplate/index.js
  web/src/components/template/index.js
  web/src/images/stage/template_default.png
  web/src/layout/Breadcrumb.js
  web/src/layout/index.js
  web/src/less/index.less
  web/src/locale/en-US.json
  web/src/locale/zh-CN.json
  web/src/routes/index.js
  web/src/store/index.js
  web/src/store/stageTemplate.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#730 feat:add OAuth authType for Oauth way to create project
  pkg/api/types.go
  pkg/scm/scm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#725 docs: add roadmap
  docs/ROADMAP.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#721 Add arch design doc
  docs/design.md
  docs/images/cyclone-arch.png
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#727 Update git ignore
  .gitignore
Labels: caicloud-cla: yes, release-note-none, size/XS

#732 docs: update CONTRIBUTING docs to add go lint
  CONTRIBUTING.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#723 feat(api): add api to support operate tenant
  cmd/server/main.go
  pkg/server/apis/v1alpha1/descriptors/resource.go
  pkg/server/apis/v1alpha1/descriptors/stage.go
  pkg/server/apis/v1alpha1/descriptors/tenant.go
  pkg/server/apis/v1alpha1/descriptors/workflow.go
  pkg/server/apis/v1alpha1/descriptors/workflowrun.go
  pkg/server/apis/v1alpha1/descriptors/workflowtrigger.go
  pkg/server/apis/v1alpha1/types.go
  pkg/server/config/config.go
  pkg/server/handler/common/const.go
  pkg/server/handler/common/handler.go
  pkg/server/handler/handler.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/stage.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
  pkg/util/http/http.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#729 Enhance the update of stage status
  pkg/workflow/controller/handlers/pod/operation.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#735 fix: fix coordinator can not connect to cyclone server
  manifests/cyclone.yaml
  release/cyclone-server.yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#736 feat(api): add api for integration
  pkg/server/apis/v1alpha1/descriptors/integration.go
  pkg/server/apis/v1alpha1/types.go
  pkg/server/common/cluster.go
  pkg/server/common/const.go
  pkg/server/common/utils.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/tenant.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#742 fix: use docker hub in Makefile
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#737 Stage templates manifests
  .dockerignore
  Gopkg.lock
  Makefile
  build/server/Dockerfile
  cmd/server/main.go
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/code-scan.yaml
  manifests/templates/cicd/image-build.yaml
  manifests/templates/cicd/unit-test.yaml
  pkg/server/biz/templates/stages.go
  pkg/server/biz/tenants/templates.go
  pkg/server/biz/utils/file.go
  pkg/server/handler/v1alpha1/tenant.go
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#743 chore: add dev mode to workflow controller
  manifests/cyclone.yaml
  pkg/workflow/controller/config.go
  pkg/workflow/workflowrun/pod.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#744 fix: use bash in make
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#712 feat(*): add project form
  web/.eslintrc
  web/mock/example.js
  web/package.json
  web/src/api/index.js
  web/src/components/integration/component/List.js
  web/src/components/project/component/AddProject.js
  web/src/components/project/component/List.js
  web/src/components/project/component/addProject/Form.js
  web/src/components/project/component/addProject/IntegrationSelect.js
  web/src/components/project/component/addProject/index.js
  web/src/components/project/index.js
  web/src/components/public/consts/const.js
  web/src/components/public/consts/regexp.js
  web/src/components/public/consts/validate.js
  web/src/components/public/inputWithUnit/InputWithUnit.js
  web/src/components/public/inputWithUnit/index.js
  web/src/components/public/makeField/Field.js
  web/src/components/public/makeField/index.js
  web/src/components/public/resourceAllocation/Allocation.js
  web/src/components/public/resourceAllocation/index.js
  web/src/components/public/validate/index.js
  web/src/less/inc.var.less
  web/src/less/index.less
  web/src/less/p.project.less
  web/src/less/u.detail.less
  web/src/less/u.inputWithUnit.less
  web/src/less/u.resourceAllocation.less
  web/src/locale/en-US.json
  web/src/locale/zh-CN.json
  web/src/store/integration.js
  web/src/store/workflow.js
  web/src/utils/index.js
  web/yarn.lock
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#745 chores: update Makefile for deploy and undeploy
  .dockerignore
  Makefile
  README.md
  manifests/cyclone.yaml.template
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#746 fix(*): fix mobx does not contain an export named useStrict error
  web/src/components/project/component/addProject/IntegrationSelect.js
  web/src/less/inc.var.less
  web/src/store/stageTemplate.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#749 feat: add project API
  manifests/crd.yaml
  pkg/apis/cyclone/v1alpha1/crd.go
  pkg/apis/cyclone/v1alpha1/project.go
  pkg/apis/cyclone/v1alpha1/register.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/cyclone_client.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_cyclone_client.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_project.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/generated_expansion.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/project.go
  pkg/k8s/informers/cyclone/v1alpha1/interface.go
  pkg/k8s/informers/cyclone/v1alpha1/project.go
  pkg/k8s/informers/generic.go
  pkg/k8s/listers/cyclone/v1alpha1/expansion_generated.go
  pkg/k8s/listers/cyclone/v1alpha1/project.go
  pkg/server/apis/v1alpha1/descriptors/project.go
  pkg/server/apis/v1alpha1/types.go
  pkg/server/handler/v1alpha1/project.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#750 feat(*): connect back-end
  web/package.json
  web/src/components/integration/component/List.js
  web/src/store/integration.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#752 refactor(i18n): convert json to yaml
  web/config/webpack.config.dev.js
  web/config/webpack.config.prod.js
  web/package.json
  web/src/index.js
  web/src/locale/en-US.json
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.json
  web/src/locale/zh-CN.yaml
  web/yarn.lock
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#747 feat(project): list project and add project with back-end
  web/src/api/http.js
  web/src/api/index.js
  web/src/components/project/component/List.js
  web/src/components/project/component/ProjectDetail.js
  web/src/components/project/component/addProject/Form.js
  web/src/components/project/component/addProject/IntegrationSelect.js
  web/src/components/public/consts/validate.js
  web/src/components/public/ellipsisMenu/index.js
  web/src/components/public/inputWithUnit/InputWithUnit.js
  web/src/components/public/makeField/Field.js
  web/src/components/public/quota/Quota.js
  web/src/components/public/quota/index.js
  web/src/components/public/resourceAllocation/index.js
  web/src/less/inc.var.less
  web/src/store/index.js
  web/src/store/project.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#754 feat(*): separate project form and add moment dependency
  web/package.json
  web/src/components/integration/component/List.js
  web/src/components/project/component/List.js
  web/src/components/project/component/ProjectDetail.js
  web/src/components/project/component/addProject/Form.js
  web/src/components/project/component/addProject/FormContent.js
  web/src/components/project/component/addProject/FormWrap.js
  web/src/components/project/component/addProject/IntegrationSelect.js
  web/src/components/project/component/addProject/index.js
  web/src/components/public/inputWithUnit/InputWithUnit.js
  web/src/components/public/quota/QuotaSetting.js
  web/src/components/public/quota/index.js
  web/src/consts/const.js
  web/src/consts/regexp.js
  web/src/consts/validate.js
  web/src/less/inc.var.less
  web/src/lib/util.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/project.js
  web/yarn.lock
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#755 chore: add React into ProvidePlugin
  web/config/webpack.config.prod.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#759 feat(*): project update
  web/src/api/index.js
  web/src/components/project/component/List.js
  web/src/components/project/component/ProjectDetail.js
  web/src/components/project/component/addProject/FormContent.js
  web/src/components/project/component/addProject/FormWrap.js
  web/src/components/project/component/addProject/IntegrationSelect.js
  web/src/components/project/index.js
  web/src/components/public/inputWithUnit/InputWithUnit.js
  web/src/components/public/quota/Form.js
  web/src/components/public/quota/QuotaSetting.js
  web/src/consts/validate.js
  web/src/store/integration.js
  web/src/store/project.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#760 perf(*): extract menu actions as a component
  web/src/components/project/component/List.js
  web/src/components/project/component/MenuAction.js
  web/src/components/project/component/ProjectDetail.js
  web/src/components/project/component/addProject/FormWrap.js
  web/src/components/project/index.js
  web/src/components/public/ellipsisMenu/index.js
  web/src/store/project.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#762 feat(project): validate project quota
  web/package.json
  web/src/components/project/component/addProject/FormContent.js
  web/src/components/project/component/addProject/FormWrap.js
  web/src/components/project/component/addProject/IntegrationSelect.js
  web/src/components/public/inputWithUnit/InputWithUnit.js
  web/src/components/public/makeField/Field.js
  web/src/components/public/quota/Form.js
  web/src/components/public/quota/QuotaSetting.js
  web/src/components/public/validate/index.js
  web/src/consts/validate.js
  web/src/less/p.project.less
  web/src/less/u.inputWithUnit.less
  web/src/less/u.resourceAllocation.less
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/yarn.lock
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#766 feat(*): add resource list and stage list
  web/src/api/index.js
  web/src/components/integration/component/DataForm.js
  web/src/components/integration/component/List.js
  web/src/components/project/component/addProject/IntegrationSelect.js
  web/src/components/project/component/detail/index.js
  web/src/components/project/component/detail/resource.js
  web/src/components/project/component/detail/stage.js
  web/src/components/project/index.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/project.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#768 feat(*): modify project name to alias and fix some proptypes warning
  web/src/components/project/component/List.js
  web/src/components/project/component/MenuAction.js
  web/src/components/project/component/addProject/FormContent.js
  web/src/components/project/component/addProject/FormWrap.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#771 feat(*): perfect quota validate text
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: caicloud-cla: yes, lgtm, release-note-none, size/XS

#767 fix(api): unify metadata of cyclone resources
  pkg/server/apis/v1alpha1/types.go
  pkg/server/common/cluster.go
  pkg/server/common/const.go
  pkg/server/common/utils.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/stage.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#769 Add cicd examples
  .gitignore
  Makefile
  README.md
  examples/cicd/generate.sh
  examples/cicd/golang/manifests.yaml.template
  manifests/cyclone.yaml
  manifests/cyclone.yaml.template
  manifests/examples/ci.yaml
  manifests/examples/simple.yaml
  manifests/examples/wfr.yaml
  manifests/generate.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#775 chores: improve cyclone web styles
  web/src/components/project/component/addProject/FormContent.js
  web/src/components/project/component/addProject/IntegrationSelect.js
  web/src/components/stageTemplate/List/Item.js
  web/src/images/stage/template_default.png
  web/src/less/p.project.less
Labels: caicloud-cla: yes, lgtm, release-note-none, size/M

#776 fix: display project alias instead of name
  web/src/components/project/component/List.js
  web/src/components/project/component/detail/index.js
  web/src/components/resource/index.js
  web/src/layout/index.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#777 fix: remove resource route
  web/src/routes/index.js
Labels: caicloud-cla: yes, release-note-none

#778 fix: tyo in readme
  README.md
Labels: caicloud-cla: yes, release-note-none, size/XS

#779 chores: add ci examples for nodejs, java
  examples/cicd/generate.sh
  examples/cicd/golang/manifests.yaml.template
  examples/cicd/java/manifests.yaml.template
  examples/cicd/nodejs/manifests.yaml.template
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
