Repository caicloud/cyclone, pull requests merged in 2019-09, with the labels that each got.

#1272 chores(makefile): add ut coverage for make test
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1281 fix: overall status judgement when multiple stage errors
  pkg/workflow/workflowrun/operator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1282 fix: close websocket when workflow run running completed
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/util/websocket/websocket.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1285 [CPS-2.8] fix: eof of stage logs FolderReader
  cmd/workflow/coordinator/main.go
  pkg/common/const.go
  pkg/server/biz/stream/folder.go
  pkg/server/biz/stream/folder_test.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/util/websocket/websocket.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/cycloneserver/client.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1291 docs(readme): update invitation link of slack
  README.md
Labels: caicloud-cla: yes, release-note-none, size/XS
