Repository caicloud/cyclone, pull requests merged in 2019-08, with the labels that each got.

#1211 fix: set http.postBuffer for git resolver
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1212 feat: collect realtime init container logs
  helm/cyclone/templates/controller.yaml
  pkg/workflow/common/const.go
  pkg/workflow/controller/config.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1210 fix(log-stream): websocket interrupted occasionally
  cmd/toolbox/fstream/main.go
  pkg/server/apis/v1alpha1/descriptors/workflowrun.go
  pkg/server/biz/stream/folder.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/util/websocket/websocket.go
  pkg/workflow/coordinator/cycloneserver/client.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1214 fix: workflow run status check logic
  pkg/workflow/controller/handlers/pod/operation.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1215 fix: bitbucket pr webhook problem
  build/resolver/git/entrypoint.sh
  pkg/server/biz/scm/bitbucket/server/webhooks.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1217 fix: gitlab version detect problem
  pkg/server/biz/scm/gitlab/gitlab.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1218 fix: validate bitbucket token
  pkg/server/biz/scm/bitbucket/server/server.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1219 fix: GitLab tag deletion should not trigger workflow
  pkg/server/biz/scm/gitlab/gitlab.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1220 fix: workflow run status check logic
  pkg/workflow/controller/handlers/pod/operation.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1222 fix: use error with reason for token validation fail
  pkg/server/biz/scm/bitbucket/server/server.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1223 fix: use authorization error to token validation fail
  pkg/server/biz/scm/bitbucket/server/server.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1245 fix: init pull request status when wfr start
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1247 fix: send notification only once
  pkg/workflow/controller/handlers/workflowrun/handler.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1249 fix: git clone from bitbucket failed
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1252 fix: add target branch for list pull requests api
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/biz/scm/scm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1253 fix: specify connection refused error
  pkg/server/biz/scm/bitbucket/server/server.go
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1251 fix: defer exit to collect init containers' logs
  build/toolbox/Dockerfile
  build/toolbox/resolver-runner.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1254 fix(panic): call of reflect.Value.IsNil on zero Value
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1260 fix: out of range panic protection
  pkg/server/handler/v1alpha1/admin.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/stage.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
  pkg/server/handler/v1alpha1/workload.go
  pkg/server/types/common.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1263 chore: enable PVC watcher
  pkg/server/biz/integration/cluster/cluster.go
  pkg/server/biz/pvc/pvc.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1262 fix: image tag wrong when workflow triggered by bitbucket release
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1266 feat: add execution contexts api
  pkg/server/apis/v1alpha1/descriptors/tenant.go
  pkg/server/apis/v1alpha1/types.go
  pkg/server/handler/v1alpha1/executioncontext.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/L

#1268 test: add tests for pvc watcher
  pkg/server/biz/usage/usage.go
  pkg/server/biz/usage/watcher.go
  pkg/server/biz/usage/watcher_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1269 fix: GitHub tag trigger problem
  pkg/server/biz/scm/github/github.go
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1273 fix: overall status wrong when stage status is cancelled
  pkg/workflow/workflowrun/operator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XS

#1274 chore: add mount propagation
  release/cyclone-server.yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1276 fix: resync of wfr
  pkg/workflow/controller/controllers/configmap.go
  pkg/workflow/controller/controllers/controller.go
  pkg/workflow/controller/controllers/exucution_cluster.go
  pkg/workflow/controller/controllers/pod.go
  pkg/workflow/controller/controllers/workflow_trigger.go
  pkg/workflow/controller/controllers/workflowrun.go
  pkg/workflow/controller/handlers/configmap/handler.go
  pkg/workflow/controller/handlers/executioncluster/handler.go
  pkg/workflow/controller/handlers/interface.go
  pkg/workflow/controller/handlers/pod/handler.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/controller/handlers/workflowtrigger/handler.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
