Repository caicloud/cyclone, pull requests merged in 2019-06, with the labels that each got.

#1070 feat: support arbitrary resource type
  helm/cyclone/templates/resource-type.yaml
  pkg/apis/cyclone/v1alpha1/common.go
  pkg/apis/cyclone/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/resourcetypes.go
  pkg/workflow/common/resource_resolver.go
  pkg/workflow/controller/config.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1071 feat: wfr status tag and duration
  web/src/components/resource/component/create/index.js
  web/src/components/workflow/component/detail/WorkflowRuns.js
  web/src/lib/util.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1069 fix: skip notifications for workflowruns without trigger
  pkg/server/handler/v1alpha1/notification.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1074 feat(workflow): default stage/resource name
  web/src/components/workflow/component/add/Form.js
  web/src/components/workflow/component/detail/StageDepend.js
  web/src/components/workflow/component/detail/WorkflowDetail.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/StageField.js
  web/src/components/workflow/component/stage/TemplateStage.js
  web/src/lib/const.js
  web/src/lib/util.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1073 feat: bind resource type to integration type
  helm/cyclone/templates/resource-type.yaml
  pkg/apis/cyclone/v1alpha1/resource.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  web/src/components/project/component/detail/index.js
  web/src/components/resource/component/List.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1075 feat: api doc link to headerbar
  web/src/layout/index.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1076 feat: project list api supports searching
  pkg/server/handler/v1alpha1/project.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1077 feat(resource): use integration in resoure create
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/store/resource.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1080 feat(*): add project/workflow/workflowruns search
  web/src/api/index.js
  web/src/components/project/component/List.js
  web/src/components/project/component/detail/index.js
  web/src/components/workflow/component/detail/WorkflowRuns.js
  web/src/components/workflow/component/list/ListLayout.js
  web/src/components/workflow/component/list/WorkflowTable.js
  web/src/less/inc.var.less
  web/src/store/integration.js
  web/src/store/project.js
  web/src/store/workflow.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1079 feat: implement overview page
  .gitignore
  package-lock.json
  pkg/server/handler/v1alpha1/admin.go
  web/package.json
  web/src/api/index.js
  web/src/components/overview/index.js
  web/src/less/inc.var.less
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/dashboard.js
  web/src/store/index.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#1084 fix: resource type page error
  web/src/components/resource/component/List.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1083 chore(integration): replace integration const js & fix template bug
  web/src/components/integration/component/createIntegration/FormWrap.js
  web/src/components/stageTemplate/add/Form.js
  web/src/consts/const.js
  web/src/lib/const.js
Labels: approved, lgtm

#1085 feat: wfr version generation
  web/src/components/workflow/component/RunWorkflow.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1089 chore(project): remove quota config field
  web/src/components/project/component/addProject/FormContent.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1088 fix(project): fix project detail workflow url path
  web/src/components/workflow/component/list/WorkflowTable.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1086 refact: remove suffix of stage template names
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/cd.yaml
  manifests/templates/cicd/image-build.yaml
  manifests/templates/cicd/sonarqube.yaml
  manifests/templates/cicd/unit-test.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1090 fix webhook issue
  cmd/workflow/coordinator/main.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
Labels: approved, lgtm

#1093 feat: add SCM_REPO to git resource
  build/resolver/git/entrypoint.sh
  helm/cyclone/templates/resource-type.yaml
Labels: caicloud-cla: yes, lgtm, release-note-none, size/S

#1092 fix(integration): fix integration form wrong alias & detail
  web/src/components/integration/component/List.js
  web/src/components/integration/component/createIntegration/FormWrap.js
  web/src/components/integration/component/detail/index.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1094 fix: display list in descending order of creation
  web/src/components/integration/component/List.js
  web/src/components/project/component/detail/index.js
  web/src/components/workflow/component/detail/WorkflowRuns.js
  web/src/components/workflow/component/list/ListLayout.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1091 fix(workflow): add section card to resource form in workflow
  web/src/components/workflow/component/resource/BindResource.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1096 feat: add status filter to wfr list
  web/src/components/workflow/component/detail/WorkflowRuns.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1095 fix: fix special character in cmd
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/image-build.yaml
  manifests/templates/cicd/unit-test.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1097 fix: edit resource in stage
  web/src/components/workflow/component/resource/Form.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1098 fix: add wf count in project list
  pkg/apis/cyclone/v1alpha1/project.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/types/common.go
  web/src/components/project/component/List.js
  web/src/components/project/component/MenuAction.js
  web/src/components/project/component/addProject/FormWrap.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1102 feat: support secret, cm preset volumes
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/server/biz/accelerator/accelerate.go
  pkg/server/biz/accelerator/accelerate_test.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
  pkg/workflow/workload/pod/util.go
Labels: approved, caicloud-cla: yes, lgtm, size/L

#1101 fix(devops): not post arguments description info
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/TemplateStage.js
  web/src/store/stageTemplate.js
  web/yarn.lock
Labels: approved, caicloud-cla: yes, lgtm, size/XL

#1104 [CherryPick] feat: support secret, cm preset volumes
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/server/biz/accelerator/accelerate.go
  pkg/server/biz/accelerator/accelerate_test.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
  pkg/workflow/workload/pod/util.go
Labels: caicloud-cla: yes, lgtm, release-note-none, size/L

#1105 chore(*): drawer formItem Layout
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/StageField.js
  web/src/components/workflow/component/stage/TemplateStage.js
  web/src/lib/const.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1100 chore(resource): forbidden bulit in resource edited & deleted
  web/src/components/public/ellipsisMenu/index.js
  web/src/components/resource/component/List.js
  web/src/components/resource/component/MenuAction.js
  web/src/components/stageTemplate/add/FormContent.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1103 chore(workflow): add loop request while nonterminated status
  web/src/api/http.js
  web/src/components/workflow/component/RunWorkflow.js
  web/src/components/workflow/component/detail/WorkflowRuns.js
  web/src/store/workflow.js
Labels: approved, caicloud-cla: yes, lgtm, size/L

#1107 feat(workflow): remove workflow side menu and modify breadcrumb
  web/src/components/project/component/MenuAction.js
  web/src/components/project/component/addProject/FormContent.js
  web/src/components/project/component/addProject/FormWrap.js
  web/src/components/project/component/detail/index.js
  web/src/components/project/index.js
  web/src/components/workflow/component/MenuAction.js
  web/src/components/workflow/component/add/Form.js
  web/src/components/workflow/component/add/util.js
  web/src/components/workflow/component/detail/WorkflowDetail.js
  web/src/components/workflow/component/list/ListLayout.js
  web/src/components/workflow/component/list/WorkflowTable.js
  web/src/components/workflow/component/list/index.js
  web/src/components/workflow/index.js
  web/src/layout/Breadcrumb.js
  web/src/layout/index.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/routes/index.js
  web/src/store/workflow.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1087 feat(resourceType): add integration type to resourceType
  web/src/components/resource/component/create/FormContent.js
  web/src/components/resource/component/create/SelectSourceType.js
  web/src/components/resource/component/create/index.js
  web/src/components/resource/component/detail/index.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1108 fix(workflow): workflow name read only when update
  web/src/components/workflow/component/add/BasicInfo.js
  web/src/components/workflow/component/add/CreateWorkflow.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1109 fix(resource): resource array field name error
  web/src/components/workflow/component/stage/StageField.js
  web/src/components/workflow/component/stage/TemplateStage.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1110 fix(devops): custom stage resource array field name error
  web/src/components/workflow/component/stage/StageField.js
  web/src/components/workflow/component/stage/TemplateStage.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1111 fix: use resolvers in config file
  pkg/apis/cyclone/v1alpha1/resource.go
  pkg/workflow/common/resource_resolver.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1118 feat(resource): create/update resource in project
  web/src/components/project/component/detail/index.js
  web/src/components/project/component/detail/resource.js
  web/src/components/public/makeField/Field.js
  web/src/components/resource/component/Form.js
  web/src/components/resource/component/FormContent.js
  web/src/components/resource/component/List.js
  web/src/components/resourceTypes/component/List.js
  web/src/components/resourceTypes/component/MenuAction.js
  web/src/components/resourceTypes/component/create/FormContent.js
  web/src/components/resourceTypes/component/create/SelectSourceType.js
  web/src/components/resourceTypes/component/create/index.js
  web/src/components/resourceTypes/component/detail/index.js
  web/src/components/resourceTypes/index.js
  web/src/components/workflow/component/add/Form.js
  web/src/components/workflow/component/add/util.js
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/resource/ResourceArray.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/StageField.js
  web/src/components/workflow/component/stage/TemplateStage.js
  web/src/lib/util.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/routes/index.js
  web/src/store/project.js
  web/src/store/resource.js
  yarn-error.log
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#1117 fix(#1114): support multiple level scm repo
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1120 fix(workflow): delete stage at workflow update
  web/src/components/workflow/component/add/Graph.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/resource.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1121 fix(stage): stage config command
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/add/util.js
  web/src/components/workflow/component/stage/StageField.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1122 fix(#1116): fix acceleration for auto triggered workflowruns
  pkg/server/handler/v1alpha1/webhook.go
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1125 fix ci problem
  pkg/server/biz/scm/bitbucket/server/server.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1124 fix(workflow): remove workflow stage artifacts and fix stage depends
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/add/util.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1126 feat: configre dind sidercar and fix parameter value template
  helm/cyclone/templates/controller.yaml
  pkg/workflow/controller/config.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1127 fix: npm packages for vulnerabilities
  web/package.json
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1130 chore: update helm for v1.0.0-alpha
  Makefile
  README.md
  helm/cyclone/Chart.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1129 chore: add cyclone web user guide
  docs/images/screenshots/add-integration.png
  docs/images/screenshots/add-resource-type.png
  docs/images/screenshots/create-resource.png
  docs/images/screenshots/overview.png
  docs/images/screenshots/project-detail.png
  docs/images/screenshots/resource-types.png
  docs/images/screenshots/template-detail.png
  docs/images/screenshots/templates.png
  docs/images/screenshots/workflow-basic.png
  docs/images/screenshots/workflow-records.png
  docs/images/screenshots/workflow-update.png
  docs/user-guide-web.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1133 fix: some cyclone web problems
  web/src/api/http.js
  web/src/components/resourceTypes/component/List.js
  web/src/components/workflow/component/list/WorkflowTable.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1135 enhance: improve scm list api performance
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/biz/scm/helper.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1138 fix: unknown Cancelled status
  build/watcher/pvc-watcher.sh
  pkg/workflow/workflowrun/operator.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1136 fix: filter sensitive infomation
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1141 fix: storage usage report from user cluster
  pkg/server/biz/pvc/pvc.go
  pkg/server/biz/usage/watcher.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1142 fix: support append container logs
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1145 fix: generate image random tag
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1149 fix: argument escape problem
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1148 fix: update tenant pvc not found error
  pkg/server/biz/pvc/pvc.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1151 feat: support global variable
  pkg/apis/cyclone/v1alpha1/workflow.go
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/common/values/generators.go
  pkg/common/values/generators_test.go
  pkg/common/values/nowtime.go
  pkg/common/values/nowtime_test.go
  pkg/common/values/random.go
  pkg/common/values/random_test.go
  pkg/server/handler/v1alpha1/notification.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/values/ref/ref.go
  pkg/workflow/values/ref/ref_test.go
  pkg/workflow/values/ref/secret.go
  pkg/workflow/values/ref/secret_test.go
  pkg/workflow/values/ref/stage.go
  pkg/workflow/values/ref/variable.go
  pkg/workflow/values/ref/variable_test.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/secret_test.go
  pkg/workflow/workload/pod/util.go
  pkg/workflow/workload/pod/util_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#1147 feat(#1099): support enterprise Github
  pkg/server/biz/scm/github/github.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1153 fix: fix a Prettier error
  web/src/components/stageTemplate/add/Input.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1154 docs: fix contributing md error
  CONTRIBUTING.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1157 fix: resources not freed immediately after stage finished
  pkg/common/values/nowtime_test.go
  pkg/util/retry/retry.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/workload.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1160 [release-1.0] fix: resources not freed immediately after stage finished
  pkg/util/retry/retry.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/workload.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1159 chore: styles, comments and values docs
  docs/concepts/values.md
  pkg/apis/cyclone/v1alpha1/workflow.go
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/common/values/generators.go
  pkg/common/values/generators_test.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/values/ref/ref.go
  pkg/workflow/values/ref/ref_test.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1161 chore: get record web url template from env firstly
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/helper.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1163 fix: last line log would be missing if not ended with \n
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1156 refactor: use mkdir to acquire lock in git resolver
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1164 fix: assign resource requirements of cyclone containers with 0
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1155 fix: update image tag rule for webhook triggered pipeline
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1166 fest: skip ssl verify for gitlab
  pkg/server/biz/scm/gitlab/gitlab.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1165 feat(oauth): cherry-pick from v0.8 to v0.9
  pkg/server/apis/api.go
  pkg/server/apis/v1/descriptors/descriptor.go
  pkg/server/apis/v1/descriptors/oauth.go
  pkg/server/apis/v1/handler/oauth.go
  pkg/server/apis/v1/types.go
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/biz/scm/scm.go
  pkg/util/http/http.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL
