Repository caicloud/cyclone, pull requests merged in 2019-11, with the labels that each got.

#1318 fix: reduce cpu usage caused by go ticker incorrect use
  pkg/workflow/workflowrun/limits.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1313 fix: workflow topology lost problem
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/workflowrun/operator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1319 chore(release): adjust resource quota
  release/cyclone-server.yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1321 fix: deleting pod stuck on Terminating status
  pkg/meta/labels.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1309 fix(devops): update workflow display form is incorrect
  web/src/components/workflow/component/stage/AddStage.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1335 fix: address code review comments for workflowRun parallelism
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/workflowrun/parallelism.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1330 feat(server): PR events support specify target branch
  pkg/apis/cyclone/v1alpha1/workflow_trigger.go
  pkg/server/biz/scm/bitbucket/server/webhooks.go
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1331 feat(api): record pvc usage in list executioncontexts api
  pkg/server/apis/v1alpha1/types.go
  pkg/server/biz/usage/usage.go
  pkg/server/handler/v1alpha1/executioncontext.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1336 fix: delete branch should not trigger workflowrRun
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlab.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
