Repository caicloud/cyclone, pull requests merged in 2019-04, with the labels that each got.

#882 feat: skip ssl verify
  pkg/scm/provider/github/github.go
  pkg/worker/scm/provider/git.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#883 fix: fix acceleration covered preset volumes
  pkg/server/biz/accelerator/accelerate.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#884 fix: ensure protocol scheme added in url
  pkg/util/http/http.go
  pkg/workflow/workload/delegation/delegate.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#881 refactor: normalize definition of annotations and labels
  build/resolver/git/entrypoint.sh
  examples/cicd/golang/manifests.yaml.template
  examples/cicd/java/manifests.yaml.template
  examples/cicd/nodejs/manifests.yaml.template
  manifests/crd.yaml
  manifests/cyclone.yaml.template
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/cd.yaml
  manifests/templates/cicd/code-scan.yaml
  manifests/templates/cicd/image-build.yaml
  manifests/templates/cicd/unit-test.yaml
  pkg/apis/cyclone/v1alpha1/doc.go
  pkg/apis/cyclone/v1alpha1/register.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/cyclone_client.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_project.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_resource.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_stage.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_workflow.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_workflowrun.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_workflowtrigger.go
  pkg/k8s/informers/generic.go
  pkg/meta/annotations.go
  pkg/meta/labels.go
  pkg/meta/labels_test.go
  pkg/server/biz/accelerator/accelerate.go
  pkg/server/biz/accelerator/accelerate_test.go
  pkg/server/biz/usage/usage.go
  pkg/server/biz/usage/watcher.go
  pkg/server/common/cluster.go
  pkg/server/common/const.go
  pkg/server/common/utils.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/stage.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/usage.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
  pkg/server/handler/v1alpha1/workload.go
  pkg/workflow/common/const.go
  pkg/workflow/controller/controllers/pod.go
  pkg/workflow/controller/handlers/pod/gc.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
  web/src/components/integration/component/List.js
  web/src/components/integration/component/createIntegration/FormWrap.js
  web/src/components/integration/component/detail/index.js
  web/src/components/project/component/List.js
  web/src/components/project/component/addProject/FormWrap.js
  web/src/components/project/component/detail/index.js
  web/src/components/stageTemplate/List/Item.js
  web/src/components/stageTemplate/List/index.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#887 chore: list system builtin templates with builtin label
  pkg/meta/labels.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#886 fix: change system tenant name from 'admin' to 'system'
  pkg/server/common/const.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#888 feat(cron-trigger): support more types of cron expressions
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#889 feat: keep stage templates in cyclone system namespace
  cmd/server/main.go
  manifests/cyclone.yaml.template
  pkg/server/biz/templates/templates.go
  pkg/server/common/const.go
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/template.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#890 feat: make creating default tenant configurable
  cmd/server/main.go
  manifests/cyclone.yaml.template
  pkg/server/common/const.go
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/tenant.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#891 fix: init stages status in wfr
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#893 feat(#892): search and filter stage templates
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#895 feat(#894): add apis to list repos/branches/tags for integrated scms
  pkg/server/apis/v1alpha1/descriptors/integration.go
  pkg/server/biz/scm/scm.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
Labels: approved, caicloud-cla: yes, release-note-none, size/L

#897 feat(#896): store notification status in workflowrun
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/config_test.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
Labels: caicloud-cla: yes, lgtm, release-note-none, size/L

#899 fix: rename template query type to keep consistent with label
  pkg/server/handler/v1alpha1/template.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#900 fix: gc pod memory quota limit
  build/resolver/git/entrypoint.sh
  pkg/workflow/workflowrun/operator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#901 chore: update release yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#906 feat(workflow): add diagraph with workflow
  web/package.json
  web/src/components/stageTemplate/List/index.js
  web/src/components/workflow/component/CreateWorkFlow.js
  web/src/components/workflow/component/Graph.js
  web/src/components/workflow/component/List.js
  web/src/components/workflow/component/graph-config.js
  web/src/components/workflow/component/index.js
  web/src/components/workflow/index.js
  web/yarn.lock
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#903 fix: wfr overall status when still some stage pending
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/operator_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#902 fix: delete logs in pvc while deleting associated cyclone resources
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#911 fix: pod controller miss gc pods
  pkg/meta/labels.go
  pkg/workflow/controller/controllers/pod.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#910 fix: add project owner reference
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/stage.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#912 feat(trigger-api): make workflowtrigger as a sub-resource of workflow
  pkg/server/apis/v1alpha1/descriptors/workflowtrigger.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#905 chore: add pod resources
  release/cyclone-server.yaml
  release/cyclone-web.yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#898 feat: add api to cleanup storage
  manifests/cyclone.yaml.template
  pkg/server/apis/v1alpha1/descriptors/storage.go
  pkg/server/apis/v1alpha1/descriptors/usage.go
  pkg/server/apis/v1alpha1/types.go
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/storage.go
  pkg/server/handler/v1alpha1/usage.go
  pkg/workflow/workflowrun/operator.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#918 feat: add precise error to indicate scm internal error
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/biz/scm/scm.go
  pkg/server/biz/scm/svn/svn.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#917 feat: support wfr cancel
  pkg/server/apis/v1alpha1/descriptors/workflowrun.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#914 feat(server): support sort by metadata.creationTimestamp for listing
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/sorter/namespace.go
  pkg/server/handler/v1alpha1/sorter/project.go
  pkg/server/handler/v1alpha1/sorter/resource.go
  pkg/server/handler/v1alpha1/sorter/secret.go
  pkg/server/handler/v1alpha1/sorter/stage.go
  pkg/server/handler/v1alpha1/sorter/workflow.go
  pkg/server/handler/v1alpha1/sorter/workflowrun.go
  pkg/server/handler/v1alpha1/sorter/workflowtrigger.go
  pkg/server/handler/v1alpha1/stage.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
  pkg/server/types/common.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#919 fix: can not stop workflowrun
  pkg/server/handler/init.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#913 fix: apply correct resource requirements
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#920 Fix: check wfr status before cancel
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#915 feat: add notification handler
  manifests/cyclone.yaml.template
  pkg/meta/annotations.go
  pkg/meta/labels.go
  pkg/meta/labels_test.go
  pkg/server/apis/v1alpha1/descriptors/notification.go
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/biz/scm/scm.go
  pkg/server/biz/scm/svn/svn.go
  pkg/server/config/config.go
  pkg/server/config/config_test.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/notification.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/util/http/http.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/controllers/configmap.go
  pkg/workflow/controller/controllers/pod.go
  pkg/workflow/controller/controllers/workflow_trigger.go
  pkg/workflow/controller/controllers/workflowrun.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  release/cyclone-server.yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#921 chore: mount hostpath timezone
  release/cyclone-server.yaml
  release/cyclone-web.yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#926 fix: fix minor typos in docs
  README.md
  docs/design.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#927 fix(#923): ensure there are no duplicated SCM webhooks
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#933 feat: filter workflowrun by trigger
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#930 fix: should collect input resources logs
  pkg/workflow/coordinator/coordinator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#935 feat: add type to input/output resources
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/code-scan.yaml
  manifests/templates/cicd/image-build.yaml
  manifests/templates/cicd/unit-test.yaml
  pkg/apis/cyclone/v1alpha1/common.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#934 chore: add DEVELOP_MODE to release
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#936 fix: wrong ref of wfr triggered by scm tag release
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#909 feat(workflow): workflow resource and stage
  web/package.json
  web/src/components/project/component/addProject/IntegrationSelect.js
  web/src/components/public/makeField/Field.js
  web/src/components/public/sectionCard/index.js
  web/src/components/public/sectionCard/index.module.less
  web/src/components/workflow/component/CreateWorkFlow.js
  web/src/components/workflow/component/add/BasicInfo.js
  web/src/components/workflow/component/add/CreateWorkflow.js
  web/src/components/workflow/component/add/Form.js
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/add/graph-config.js
  web/src/components/workflow/component/index.js
  web/src/components/workflow/component/index.module.less
  web/src/components/workflow/component/resource/BindResource.js
  web/src/components/workflow/component/resource/Form.js
  web/src/components/workflow/component/stage/AddStage.js
  web/src/components/workflow/component/stage/StageField.js
  web/src/components/workflow/index.js
  web/src/less/inc.var.less
  web/src/lib/const.js
  web/src/lib/util.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/yarn.lock
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#908 refact: scm list api enhancement
  Gopkg.lock
  Gopkg.toml
  pkg/server/apis/v1alpha1/descriptors/integration.go
  pkg/server/biz/scm/scm.go
  pkg/server/handler/v1alpha1/integration.go
  vendor/github.com/caicloud/nirvana/CONTRIBUTING.md
  vendor/github.com/caicloud/nirvana/README.md
  vendor/github.com/caicloud/nirvana/ROADMAP.md
  vendor/github.com/caicloud/nirvana/config.json
  vendor/github.com/caicloud/nirvana/plugins/metrics/metrics.go
  vendor/github.com/caicloud/nirvana/service/builder.go
  vendor/github.com/caicloud/nirvana/service/filter.go
  vendor/github.com/caicloud/nirvana/utils/api/analyzer.go
  vendor/github.com/caicloud/nirvana/utils/api/comments.go
  vendor/github.com/caicloud/nirvana/utils/api/definitions.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#932 fix(#922): enhancement for scm error handling
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#938 fix: cluster name problem
  pkg/server/apis/v1alpha1/types.go
  pkg/server/handler/v1alpha1/integration.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#937 fix: support different token format in git resolver
  build/resolver/git/entrypoint.sh
  pkg/server/handler/v1alpha1/notification.go
  web/src/lib/const.js
Labels: caicloud-cla: yes, lgtm, release-note-none, size/M

#940 fix: update pvc size
  pkg/common/k8s.go
  pkg/server/biz/pvc/pvc.go
  pkg/server/biz/usage/watcher.go
  pkg/server/common/cluster.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/util/retry/retry.go
Labels: caicloud-cla: yes, lgtm, release-note-none, size/L

#925 docs: simple installation guide and user guide
  docs/installation.md
  docs/user_guide.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#944 feat(api): add API to open/close cluster
  pkg/server/apis/v1alpha1/descriptors/integration.go
  pkg/server/common/cluster.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#946 chore: remove secret config
  manifests/cyclone.yaml.template
  pkg/workflow/controller/config.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#948 fix: support empty argument value and escape line break
  pkg/apis/cyclone/v1alpha1/common.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/server/handler/v1alpha1/notification.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#943 feat: support svn resource
  Makefile
  build/resolver/git/entrypoint.sh
  build/resolver/image/entrypoint.sh
  build/resolver/svn/Dockerfile
  build/resolver/svn/entrypoint.sh
  examples/cicd/golang/manifests.yaml.template
  examples/cicd/java/manifests.yaml.template
  examples/cicd/nodejs/manifests.yaml.template
  manifests/cyclone.yaml.template
  pkg/apis/cyclone/v1alpha1/resource.go
  pkg/server/biz/scm/scm.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/notification.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/workflow/controller/config.go
  release/workflow-controller.yaml
  web/src/lib/const.js
Labels: caicloud-cla: yes, release-note-none, size/L

#949 fix: support git url with user in git resolver
  build/resolver/git/entrypoint.sh
Labels: caicloud-cla: yes, release-note-none, size/M

#941 feat: support configure dind parameter
  build/worker/start.sh
  cmd/worker/options/options.go
  pkg/cloud/kubernetes/kubernetes.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
