Repository caicloud/cyclone, pull requests merged in 2019-10, with the labels that each got.

#1293 fix(1292): fix out of memory of golangci-lint
  .travis.yml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1297 refact(lint): use config file for golangci-lint and fix lint errors
  .golangci.yml
  .travis.yml
  cmd/toolbox/fstream/main.go
  pkg/common/values/nowtime.go
  pkg/common/values/random.go
  pkg/meta/labels.go
  pkg/server/biz/hook/scm.go
  pkg/server/biz/integration/sonarqube/sonarqube.go
  pkg/server/biz/scm/bitbucket/bitbucket.go
  pkg/server/biz/scm/bitbucket/server/server.go
  pkg/server/biz/scm/bitbucket/server/v1Client.go
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/biz/scm/helper.go
  pkg/server/biz/scm/scm.go
  pkg/server/biz/stream/folder.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/notification.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/util/cerr/error.go
  pkg/util/websocket/websocket.go
  pkg/workflow/common/resource_resolver.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
  pkg/workflow/workflowrun/gc.go
  pkg/workflow/workflowrun/timeout.go
  pkg/workflow/workflowrun/utils.go
  pkg/workflow/workload/delegation/delegate.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1299 fix(devops): fix eslint can't read type of undefined error
  web/package.json
  web/scripts/start.js
  web/src/components/stageTemplate/add/Input.js
  web/yarn.lock
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1300 chore(*): ignore history folder
  .gitignore
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1298 [cps-2.9] fix: eof of stage logs FolderReader
  cmd/workflow/coordinator/main.go
  pkg/common/const.go
  pkg/server/biz/stream/folder.go
  pkg/server/biz/stream/folder_test.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/util/websocket/websocket.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/cycloneserver/client.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
Labels: caicloud-cla: yes, release-note-none, size/M

#1304 fix(Makefile): use config file for golangci-lint
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1290 feat(api): support start and stop pvc watcher
  pkg/server/apis/v1alpha1/descriptors/integration.go
  pkg/server/biz/integration/cluster/cluster.go
  pkg/server/biz/pvc/pvc.go
  pkg/server/biz/usage/watcher.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1303 fix(web): worklofw runs interval repeat request
  web/.eslintrc
  web/src/components/project/component/detail/stage.js
  web/src/components/workflow/component/RunWorkflow.js
  web/src/components/workflow/component/add/CreateWorkflow.js
  web/src/components/workflow/component/add/Form.js
  web/src/components/workflow/component/detail/WorkflowRuns.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1307 fix: workflow trigger controller should only process cron type trigger
  pkg/workflow/controller/handlers/workflowtrigger/handler.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1306 fix: execution context of workflow trigger expire when cluster changed
  pkg/server/biz/integration/cluster/trigger.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/workflow/workflowrun/workload.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1310 fix: maybe occur dead lock while register/unregister scm webhook
  Makefile
  pkg/server/biz/hook/scm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1312 feat: record workflow topology to workflow run
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/workflow/workflowrun/operator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1314 chore(changlog): add changelog file for CII
  CHANGELOG.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1316 fix(1315): update golangci-lint version for memory usage
  .travis.yml
  Makefile
  pkg/server/biz/integration/converter.go
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1317 fix(sonar): support extension parameters for sonar scanner
  build/cicd/sonarqube/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
