Repository caicloud/cyclone, pull requests merged in 2019-12, with the labels that each got.

#1338 fix: update pvc failed as old watchdog have not been deleting completed
  pkg/server/biz/pvc/pvc.go
  pkg/server/biz/usage/watcher.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1339 Support for gogs and change dind dockerd launch command
  .gitignore
  Gopkg.lock
  Gopkg.toml
  cmd/server/main.go
  docs/user_guide.md
  pkg/server/apis/v1alpha1/types.go
  pkg/server/biz/scm/gogs/gogs.go
  pkg/server/biz/scm/gogs/parsewebhook.go
  pkg/server/biz/scm/scm.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/workflow/workload/pod/builder.go
  vendor/github.com/gogs/go-gogs-client/.gitignore
  vendor/github.com/gogs/go-gogs-client/LICENSE
  vendor/github.com/gogs/go-gogs-client/README.md
  vendor/github.com/gogs/go-gogs-client/admin_org.go
  vendor/github.com/gogs/go-gogs-client/admin_repo.go
  vendor/github.com/gogs/go-gogs-client/admin_user.go
  vendor/github.com/gogs/go-gogs-client/gogs.go
  vendor/github.com/gogs/go-gogs-client/issue.go
  vendor/github.com/gogs/go-gogs-client/issue_comment.go
  vendor/github.com/gogs/go-gogs-client/issue_label.go
  vendor/github.com/gogs/go-gogs-client/issue_milestone.go
  vendor/github.com/gogs/go-gogs-client/media_types.go
  vendor/github.com/gogs/go-gogs-client/miscellaneous.go
  vendor/github.com/gogs/go-gogs-client/org.go
  vendor/github.com/gogs/go-gogs-client/org_member.go
  vendor/github.com/gogs/go-gogs-client/org_team.go
  vendor/github.com/gogs/go-gogs-client/pull.go
  vendor/github.com/gogs/go-gogs-client/release.go
  vendor/github.com/gogs/go-gogs-client/repo.go
  vendor/github.com/gogs/go-gogs-client/repo_branch.go
  vendor/github.com/gogs/go-gogs-client/repo_collaborator.go
  vendor/github.com/gogs/go-gogs-client/repo_commit.go
  vendor/github.com/gogs/go-gogs-client/repo_file.go
  vendor/github.com/gogs/go-gogs-client/repo_hook.go
  vendor/github.com/gogs/go-gogs-client/repo_key.go
  vendor/github.com/gogs/go-gogs-client/user.go
  vendor/github.com/gogs/go-gogs-client/user_app.go
  vendor/github.com/gogs/go-gogs-client/user_email.go
  vendor/github.com/gogs/go-gogs-client/user_follow.go
  vendor/github.com/gogs/go-gogs-client/user_key.go
  vendor/github.com/gogs/go-gogs-client/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XXL

#1341 fix: svn checkout with can't convert string from 'UTF-8' to native encoding
  build/resolver/svn/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1344 [CPS-4908]fix(cyclone): 修改邮件跳转地址
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1345 chore(*): Rebase hr onto v0.9.8-beta
  .travis.yml
  build/resolver/git/entrypoint.sh
  pkg/meta/labels.go
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/biz/scm/scm.go
  pkg/workflow/workflowrun/limits.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#1343 feat: svn post commit trigger support selecting repo
  docs/user_guide.md
  pkg/apis/cyclone/v1alpha1/workflow_trigger.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/server/biz/scm/scm.go
  pkg/server/biz/scm/svn/svn.go
  pkg/server/biz/scm/svn/svn_test.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
  pkg/util/exec/exec.go
  pkg/util/exec/exec_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-action-required, size/L

#1346 fix: first time deploy error
  helm/cyclone/templates/controller.yaml
  helm/cyclone/values.yaml
  pkg/server/handler/v1alpha1/tenant.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1337 docs: explain Kubernets resources used in Cyclone
  docs/design.md
  docs/develop/crd.md
  docs/develop/images/run-workflow-create-tenant.png
  docs/develop/images/run-workflow-create-workflow.png
  docs/develop/images/run-workflow-execute-workflow.png
  docs/develop/images/run-workflow-gc.png
  docs/develop/images/run-workflow-init.png
  docs/develop/images/run-workflow-integration-cluster.png
  docs/develop/images/run-workflow-open-cluster.png
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1348 chores(docs): update crd docs
  docs/develop/crd.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1347 fix(OAuth): Fix cannot create pipeline due to OAuth err.
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/biz/scm/scm.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/XS

#1349 feat(*): show stage log
  web/package.json
  web/src/api/index.js
  web/src/components/project/index.js
  web/src/components/public/log/Log.js
  web/src/components/public/log/index.js
  web/src/components/public/log/index.module.less
  web/src/components/public/log/network.js
  web/src/components/public/log/webSocket.js
  web/src/components/workflow/component/RunWorkflow.js
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/add/Icons.js
  web/src/components/workflow/component/detail/WorkflowDetail.js
  web/src/components/workflow/component/detail/WorkflowRuns.js
  web/src/components/workflow/component/index.module.less
  web/src/components/workflowRun/component/detail/index.js
  web/src/less/inc.var.less
  web/src/lib/util.js
  web/src/locale/en-US.yaml
  web/src/locale/zh-CN.yaml
  web/src/store/workflow.js
  web/yarn.lock
Labels: caicloud-cla: yes, lgtm, release-note-none, size/XL

#1350 fix(*): fix workflow required field and undefined func
  web/src/components/public/log/Log.js
  web/src/components/workflow/component/stage/TemplateStage.js
  web/src/layout/Breadcrumb.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1351 fix(*): running status animation
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflow/component/add/Icons.js
  web/src/components/workflowRun/component/detail/index.js
  web/src/less/inc.var.less
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1352 feat: stream log
  web/src/components/public/log/Log.js
  web/src/components/workflow/component/add/Graph.js
  web/src/components/workflowRun/component/detail/index.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1354 fix: fix output-resource-path required validate
  web/src/components/workflow/component/stage/TemplateStage.js
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1356 feat(server): make qps and brust configurable for k8s client
  cmd/server/main.go
  pkg/server/config/config.go
  pkg/util/k8s/client.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
