Repository caicloud/cyclone, pull requests merged in 2019-03, with the labels that each got.

#804 fix: add semicolon at end of line for template
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/code-scan.yaml
  manifests/templates/cicd/image-build.yaml
  manifests/templates/cicd/unit-test.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#807 fix: change cyclone server name to cyclone-server
  build/web/nginx.conf
  manifests/cyclone.yaml.template
  pkg/workflow/common/const.go
  release/cyclone-server.yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#805 feat: add start and end time for status
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/workflow/workflowrun/operator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#802 More low-level language fixes
  docs/design.md
  docs/swagger-api-docs.md
Labels: approved, caicloud-cla: no, lgtm, release-note-none, size/M

#801 minor low-level language fixes
  docs/ROADMAP.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#809 chore: build cyclone-web from local
  Makefile
  build/web/Dockerfile.local
  release/cyclone-web.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#810 feat: support resource requirements in Workflow
  pkg/apis/cyclone/v1alpha1/workflow.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/workflow/common/selector.go
  pkg/workflow/workflowrun/pod.go
  pkg/workflow/workflowrun/pod_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#811 feat: flexible image resolver and allow pass credential
  build/resolver/image/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#812 fix: controller crash as workflowRef nil when create workflowrun
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#813 chore: improve code styles
  cmd/server/main.go
  pkg/server/handler/init.go
  pkg/server/handler/v1alpha1/tenant.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#815 fix: keep startTime of status unchanged
  pkg/server/apis/v1alpha1/types.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/pod.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#814 feat: support execution context in workflowrun
  Makefile
  manifests/cyclone.yaml.template
  manifests/generate.sh
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/server/common/utils.go
  pkg/workflow/common/const.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/helper.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
  pkg/workflow/workflowrun/execution_context.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/pod.go
  pkg/workflow/workflowrun/pod_test.go
Labels: approved, caicloud-cla: yes, lgtm, size/L

#818 refactor(coordinator): coordinator get cyclone resources from env
  cmd/workflow/coordinator/main.go
  pkg/workflow/common/const.go
  pkg/workflow/common/event_recorder.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/helper.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
  pkg/workflow/workflowrun/pod.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#817 feat: support ref value from secret
  Gopkg.lock
  Gopkg.toml
  pkg/workflow/workflowrun/pod.go
  pkg/workflow/workflowrun/secret.go
  pkg/workflow/workflowrun/secret_test.go
  pkg/workflow/workflowrun/utils.go
  pkg/workflow/workflowrun/utils_test.go
  vendor/github.com/PaesslerAG/gval/.gitignore
  vendor/github.com/PaesslerAG/gval/.travis.yml
  vendor/github.com/PaesslerAG/gval/LICENSE
  vendor/github.com/PaesslerAG/gval/README.md
  vendor/github.com/PaesslerAG/gval/evaluable.go
  vendor/github.com/PaesslerAG/gval/functions.go
  vendor/github.com/PaesslerAG/gval/go.mod
  vendor/github.com/PaesslerAG/gval/go.sum
  vendor/github.com/PaesslerAG/gval/gval.go
  vendor/github.com/PaesslerAG/gval/language.go
  vendor/github.com/PaesslerAG/gval/operator.go
  vendor/github.com/PaesslerAG/gval/parse.go
  vendor/github.com/PaesslerAG/gval/parser.go
  vendor/github.com/PaesslerAG/gval/prtg-batmin-gopher.png
  vendor/github.com/PaesslerAG/gval/test.sh
  vendor/github.com/PaesslerAG/jsonpath/.gitignore
  vendor/github.com/PaesslerAG/jsonpath/.travis.yml
  vendor/github.com/PaesslerAG/jsonpath/LICENSE
  vendor/github.com/PaesslerAG/jsonpath/README.md
  vendor/github.com/PaesslerAG/jsonpath/evaluable.go
  vendor/github.com/PaesslerAG/jsonpath/go.mod
  vendor/github.com/PaesslerAG/jsonpath/go.sum
  vendor/github.com/PaesslerAG/jsonpath/jsonpath.go
  vendor/github.com/PaesslerAG/jsonpath/parse.go
  vendor/github.com/PaesslerAG/jsonpath/parser.go
  vendor/github.com/PaesslerAG/jsonpath/placeholder.go
  vendor/github.com/PaesslerAG/jsonpath/test.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#819 refactor: seperate auth to user, password in image resolver
  build/resolver/image/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#821 fix: allow anonymous user in image resolver
  build/resolver/image/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#822 refactor: shorten names
  pkg/workflow/common/const.go
  pkg/workflow/workflowrun/name.go
  pkg/workflow/workflowrun/name_test.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/pod.go
  pkg/workflow/workflowrun/pod_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#825 fix: avoid handle pod when wfr terminated
  pkg/workflow/controller/handlers/pod/operation.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#826 fix: gc when wfr deleted
  pkg/workflow/controller/controllers/workflowrun.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/workflowrun/gc.go
  pkg/workflow/workflowrun/operator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#823 feat: add workflow label for workflowrun
  pkg/server/common/const.go
  pkg/server/common/utils.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/stage.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
  pkg/workflow/common/const.go
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#824 fix(server): fix integration update panic when it does not exist
  pkg/server/handler/v1alpha1/integration.go
Labels: approved, caicloud-cla: yes, lgtm, size/XS

#816 feat(wft): refact cron trigger for workflow trigger
  pkg/apis/cyclone/v1alpha1/workflow_trigger.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#828 chore(*): update pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#831 chore: update release yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#832 fix: fix coordinator collecting logs error
  Makefile
  pkg/server/apis/v1alpha1/descriptors/workflowrun.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/util/http/http.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/cycloneserver/client.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#827 feat(server): normalize status code for server apis
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/stage.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
  pkg/util/cerr/error.go
  pkg/util/cerr/error_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#833 fix: correct produce content type of workflowrun logs
  pkg/server/apis/v1alpha1/descriptors/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#834 fix: delete tenant should close workload cluster firstly
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/tenant.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#830 chore: upgrade webpack to 4.x & dev-server to 3.2.1
  web/config/webpack.config.dev.js
  web/config/webpack.config.prod.js
  web/package.json
  web/yarn.lock
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#835 fix: change tenant prefix
  pkg/server/common/const.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/stage.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#836 feat: add CD image for update deployment
  build/cicd/cd/Dockerfile
  cmd/cicd/cd/config.json
  cmd/cicd/cd/main.go
  pkg/cicd/cd/config.go
  pkg/cicd/cd/deployment.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#838 chore: add cd template
  manifests/templates/cicd/cd.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#839 improve: use dind for image build and push
  examples/cicd/golang/manifests.yaml.template
  examples/cicd/java/manifests.yaml.template
  examples/cicd/nodejs/manifests.yaml.template
  manifests/cyclone.yaml.template
  pkg/workflow/common/const.go
  pkg/workflow/controller/config.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/workflowrun/pod.go
  pkg/workflow/workflowrun/pod_test.go
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#840 feat: support ref value of stage parameters
  manifests/templates/cicd/build.yaml
  manifests/templates/cicd/code-scan.yaml
  manifests/templates/cicd/image-build.yaml
  manifests/templates/cicd/unit-test.yaml
  pkg/workflow/common/const.go
  pkg/workflow/common/selector.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/workflowrun/pod.go
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#843 refactor(api): define status phase type
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/server/handler/init.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/workflowrun/gc.go
  pkg/workflow/workflowrun/gc_test.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/operator_test.go
  pkg/workflow/workflowrun/timeout.go
  pkg/workflow/workflowrun/utils.go
  pkg/workflow/workflowrun/utils_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#844 feat: add admin api for list all
  pkg/server/apis/v1alpha1/descriptors/admin.go
  pkg/server/handler/v1alpha1/admin.go
  pkg/util/http/http.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#842 feat(#841): Send notifications after workflowruns finish
  pkg/apis/cyclone/v1alpha1/workflow.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/workflowrun/utils.go
  pkg/workflow/workflowrun/utils_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#845 feat(api): statistics of workflowruns belongs to workflow and project
  pkg/server/apis/v1alpha1/descriptors/project.go
  pkg/server/apis/v1alpha1/descriptors/workflow.go
  pkg/server/apis/v1alpha1/types.go
  pkg/server/biz/statistic/statistic.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/util/http/http.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#847 refact(api): refact workflowrun status
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/server/apis/v1alpha1/types.go
  pkg/server/biz/statistic/statistic.go
  pkg/workflow/controller/handlers/pod/operation.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/workflowrun/gc.go
  pkg/workflow/workflowrun/gc_test.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/operator_test.go
  pkg/workflow/workflowrun/timeout.go
  pkg/workflow/workflowrun/utils.go
  pkg/workflow/workflowrun/utils_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#846 feat(server): add api to list all pods for one tenant
  pkg/server/apis/v1alpha1/descriptors/workload.go
  pkg/server/common/const.go
  pkg/server/handler/v1alpha1/workload.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#849 feat: add healthcheck api
  pkg/server/apis/v1alpha1/descriptors/healthcheck.go
  pkg/server/apis/v1alpha1/types.go
  pkg/server/handler/v1alpha1/healthcheck.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#850 fix: load templates problem
  cmd/server/main.go
  manifests/templates/cicd/cd.yaml
  pkg/server/biz/tenants/templates.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#851 fix: escape argument value
  manifests/templates/cicd/cd.yaml
  pkg/workflow/workflowrun/pod.go
Labels: approved, caicloud-cla: yes, lgtm, size/S

#852 feat: generate default container name if not set
  pkg/workflow/workflowrun/name.go
  pkg/workflow/workflowrun/pod.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#854 Delegation workload
  pkg/apis/cyclone/v1alpha1/stage.go
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/workflow/workflowrun/name.go
  pkg/workflow/workflowrun/name_test.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/utils.go
  pkg/workflow/workflowrun/utils_test.go
  pkg/workflow/workflowrun/workload.go
  pkg/workflow/workload/delegation/delegate.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
  pkg/workflow/workload/pod/secret.go
  pkg/workflow/workload/pod/secret_test.go
  pkg/workflow/workload/pod/util.go
  pkg/workflow/workload/pod/util_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#855 fix: event recorded in wfr
  pkg/workflow/workflowrun/workload.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#857 feat: supports pull reqeusts and gitlab in git resolver
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#856 feat: support preset volume for all stages
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/workflow/common/const.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#859 chore: improve code styles
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/workflow/common/const.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#860 fix: remove redundent comma in config json
  manifests/cyclone.yaml.template
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#861 feat: support building acceleration
  pkg/server/biz/accelerator/accelerate.go
  pkg/server/biz/accelerator/accelerate_test.go
  pkg/server/common/const.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#858 feat(scm): support scm trigger
  pkg/apis/cyclone/v1alpha1/workflow_trigger.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/server/apis/v1alpha1/descriptors/descriptors.go
  pkg/server/apis/v1alpha1/descriptors/webhook.go
  pkg/server/apis/v1alpha1/types.go
  pkg/server/biz/scm/github/github.go
  pkg/server/biz/scm/gitlab/gitlab.go
  pkg/server/biz/scm/gitlab/gitlabv3.go
  pkg/server/biz/scm/gitlab/gitlabv4.go
  pkg/server/biz/scm/helper.go
  pkg/server/biz/scm/scm.go
  pkg/server/biz/scm/svn/svn.go
  pkg/server/common/const.go
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/helper.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#862 Pvc usage collect
  Makefile
  build/watcher/Dockerfile
  build/watcher/pvc-watcher.sh
  cmd/server/main.go
  manifests/cyclone.yaml.template
  pkg/server/apis/v1alpha1/descriptors/usage.go
  pkg/server/apis/v1alpha1/types.go
  pkg/server/biz/statistic/usage.go
  pkg/server/biz/templates/templates.go
  pkg/server/common/const.go
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/usage.go
  pkg/util/http/http.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#864 feat: whether a stage in workflow is trivial
  pkg/apis/cyclone/v1alpha1/workflow.go
  pkg/workflow/workflowrun/utils.go
  pkg/workflow/workflowrun/utils_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#863 feat(owner): support owner and trigger
  pkg/server/biz/scm/scm.go
  pkg/server/common/const.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#865 feat: disable wfr acceleration when pvc usage exceed limit
  pkg/server/biz/accelerator/accelerate.go
  pkg/server/biz/accelerator/accelerate_test.go
  pkg/server/biz/usage/usage.go
  pkg/server/biz/usage/usage_test.go
  pkg/server/biz/usage/watcher.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/usage.go
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#866 feat(api): support search and filter
  pkg/server/handler/v1alpha1/admin.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/project.go
  pkg/server/handler/v1alpha1/resource.go
  pkg/server/handler/v1alpha1/stage.go
  pkg/server/handler/v1alpha1/template.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/workflow.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/server/handler/v1alpha1/workflowtrigger.go
  pkg/server/handler/v1alpha1/workload.go
  pkg/server/types/common.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#867 chore: update release
  release/cyclone-server.yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#868 fix: fix typo in release file
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#870 fix(engine): fix cron trigger
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#869 chore: make builtin stage templates creation configurable
  manifests/cyclone.yaml.template
  pkg/server/biz/templates/templates.go
  pkg/server/config/config.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#871 fix two small errors
  pkg/server/handler/v1alpha1/webhook.go
  pkg/workflow/controller/handlers/workflowtrigger/cron_job.go
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#873 fix: use args instead of command for dind
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#872 fix: coordinator status
  cmd/workflow/coordinator/main.go
  pkg/workflow/coordinator/coordinator.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#874 fix workflowrun alias for tag release trigger
  pkg/server/handler/v1alpha1/webhook.go
Labels: caicloud-cla: yes, lgtm, release-note-none, size/S

#876 chore: remove web build from makefile
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#877 refactor: remove kubehost option
  cmd/server/main.go
  cmd/workflow/controller/main.go
  cmd/workflow/coordinator/main.go
  pkg/util/k8s/client.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#880 fix: add missing dependency to fix web build
  web/package.json
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#879 fix: use ubuntu for git resolve to address flock problem in nfs
  build/resolver/git/Dockerfile
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
