Repository caicloud/cyclone, pull requests merged in 2020-12, with the labels that each got.

#1530 fix(*): Fix error that username or password is not correct.
  pkg/server/biz/scm/gogs/gogs.go
  pkg/util/cerr/error.go
Labels: approved, area/cicd, caicloud-cla: yes, kind/bug, lgtm, release-note, size/S

#1529 fix: cluster lost should not block close cluster
  pkg/server/biz/integration/cluster/cluster.go
  pkg/util/cerr/error.go
  pkg/workflow/controller/config.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/S

#1533 chore: update owners
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1534 Modify helm chart
  README.md
  build/server/Dockerfile
  build/server/Dockerfile.arm64
  docs/installation.md
  manifests/cyclone-public/.helmignore
  manifests/cyclone-public/Chart.yaml
  manifests/cyclone-public/templates/_helpers.tpl
  manifests/cyclone-public/templates/controller.yaml
  manifests/cyclone-public/templates/crd.yaml
  manifests/cyclone-public/templates/resource-type.yaml
  manifests/cyclone-public/templates/server.yaml
  manifests/cyclone-public/templates/service-account.yaml
  manifests/cyclone-public/templates/web.yaml
  manifests/cyclone-public/values.yaml
  manifests/cyclone/.helmignore
  manifests/cyclone/Chart.yaml
  manifests/cyclone/templates/_helpers.tpl
  manifests/cyclone/templates/controller.yaml
  manifests/cyclone/templates/server.yaml
  manifests/cyclone/values.yaml
  templates/cicd/build.yaml
  templates/cicd/cd.yaml
  templates/cicd/image-build.yaml
  templates/cicd/sonarqube.yaml
  templates/cicd/unit-test.yaml
Labels: approved, caicloud-cla: yes, kind/cleanup, lgtm, release-note-none, size/XL

#1535 fix(chart): correct images
  manifests/cyclone/templates/controller.yaml
  manifests/cyclone/templates/server.yaml
Labels: approved, area/cicd, caicloud-cla: yes, kind/bug, kind/cleanup, lgtm, release-note-none, size/S

#1536 refactor: Decouple the secret resolver from the kubernetes clientset
  Makefile
  pkg/workflow/values/ref/ref.go
  pkg/workflow/values/ref/ref_test.go
  pkg/workflow/values/ref/secret.go
  pkg/workflow/values/ref/secret_test.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, area/cicd, caicloud-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#1537 Update the name of resourceQuota to the name of its namespace
  manifests/cyclone/templates/_helpers.tpl
  manifests/cyclone/templates/controller.yaml
  manifests/cyclone/templates/server.yaml
  pkg/server/biz/integration/cluster/cluster.go
  pkg/server/common/cluster.go
  pkg/server/common/utils.go
Labels: approved, area/cicd, caicloud-cla: yes, kind/cleanup, lgtm, release-note-none, size/M

#1538 chore(manifest): unify the platform config info
  manifests/cyclone/values.yaml
Labels: approved, area/cicd, caicloud-cla: yes, kind/documentation, lgtm, release-note, size/XS

#1539 chore(*): update chart
  manifests/cyclone/templates/controller.yaml
  manifests/cyclone/templates/server.yaml
  manifests/cyclone/values.yaml
Labels: approved, area/cicd, caicloud-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#1540 chore(chart): bump version to v1.2.0-alpha.3
  manifests/cyclone/Chart.yaml
Labels: approved, area/cicd, caicloud-cla: yes, kind/upgrade, lgtm, release-note-none, size/XS

#1541 feat(webhook): cancel previous build
  Makefile
  pkg/server/handler/init.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/util/k8s/client.go
  pkg/workflow/common/event_recorder.go
Labels: approved, area/cicd, caicloud-cla: yes, kind/feature, lgtm, release-note, size/M

#1542 feat(github): retry CreateStatus on error
  pkg/server/biz/scm/github/github.go
  pkg/util/retry/retry.go
Labels: approved, area/cicd, caicloud-cla: yes, kind/feature, lgtm, release-note, size/L

#1543 [cps-2.10-infra] feat(github): retry CreateStatus
  pkg/server/biz/scm/github/github.go
  pkg/util/retry/retry.go
Labels: approved, area/cicd, caicloud-cla: yes, kind/feature, lgtm, release-note, size/S

#1545 [cps-2.10-infra] feat(webhook): cancel previous build
  pkg/server/handler/init.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/util/k8s/client.go
  pkg/workflow/common/event_recorder.go
Labels: approved, area/cicd, caicloud-cla: yes, kind/feature, lgtm, release-note-none, size/M

#1548 fix(*): do not update PR status if wfr is canceled automatically
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/server/biz/scm/github/github.go
  pkg/server/handler/v1alpha1/notification.go
  pkg/server/handler/v1alpha1/workflowrun.go
Labels: approved, area/cicd, caicloud-cla: yes, kind/bug, lgtm, release-note, size/M
