Repository caicloud/cyclone, pull requests merged in 2020-10, with the labels that each got.

#1509 fix: delete project name in workflow pod env
  pkg/workflow/common/const.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1508 feat(builder): add support for dood container
  pkg/workflow/controller/config.go
  pkg/workflow/workload/pod/builder.go
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1511 fix(resolver::git): refine repos cloning and fix `git checkout`
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1516 chore(git): add Intellij generated file to git ignore
  .gitignore
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
