Repository caicloud/cyclone, pull requests merged in 2020-11, with the labels that each got.

#1507 fix: add workflow and project name info for pods created by cyclone
  pkg/workflow/common/const.go
  pkg/workflow/common/owner.go
  pkg/workflow/common/owner_test.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1520 cps-2.8: feat(controllers): make resyncPeriod configurable
  pkg/workflow/common/const.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/controllers/exucution_cluster.go
  pkg/workflow/controller/controllers/pod.go
  pkg/workflow/controller/controllers/workflow_trigger.go
  pkg/workflow/controller/controllers/workflowrun.go
  pkg/workflow/workflowrun/limits.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1519 feat(controllers): make resyncPeriod configurable
  Makefile
  pkg/workflow/common/const.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/controllers/exucution_cluster.go
  pkg/workflow/controller/controllers/pod.go
  pkg/workflow/controller/controllers/workflow_trigger.go
  pkg/workflow/controller/controllers/workflowrun.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/workflowrun/limits.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1521 feat(controllers): make resyncPeriod configurable (#1519)
  Makefile
  pkg/workflow/common/const.go
  pkg/workflow/controller/config.go
  pkg/workflow/controller/controllers/exucution_cluster.go
  pkg/workflow/controller/controllers/pod.go
  pkg/workflow/controller/controllers/workflow_trigger.go
  pkg/workflow/controller/controllers/workflowrun.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/workflowrun/limits.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1517 fix(bitbucket): correct webhook event
  pkg/server/biz/scm/bitbucket/server/repos_webhooks.go
  pkg/server/biz/scm/bitbucket/server/server.go
  pkg/server/biz/scm/bitbucket/server/webhooks.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/M

#1524 Be able to specify extra labels or annotations of pod in stage
  helm/cyclone/templates/service-account.yaml
  pkg/apis/cyclone/v1alpha1/stage.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1526 feat(coordinator): drop the seccomp annotation before setting results
  helm/cyclone/templates/service-account.yaml
  pkg/meta/annotations.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
Labels: approved, area/cicd, caicloud-cla: yes, kind/feature, lgtm, release-note-none, size/S

#1525 fix(workflow): remove unnecessary volume from coordinator
  pkg/workflow/common/const.go
  pkg/workflow/workload/pod/builder.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1527 Refactor: change wfr spec and Reconcile method
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/server/handler/v1alpha1/notification.go
  pkg/server/handler/v1alpha1/webhook.go
  pkg/workflow/controller/controllers/controller.go
  pkg/workflow/controller/handlers/configmap/handler.go
  pkg/workflow/controller/handlers/executioncluster/handler.go
  pkg/workflow/controller/handlers/interface.go
  pkg/workflow/controller/handlers/pod/handler.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/controller/handlers/workflowtrigger/handler.go
  pkg/workflow/controller/result.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
  tools/generator/informer-gen/generators/generic.go
Labels: approved, area/cicd, caicloud-cla: yes, kind/cleanup, lgtm, release-note-none, size/L

#1528 feat(wfr): retry creating pod on QuotaExceed error until timeout
  pkg/workflow/controller/controllers/controller.go
  pkg/workflow/controller/result.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workflowrun/utils.go
  pkg/workflow/workflowrun/workload.go
Labels: approved, area/cicd, caicloud-cla: yes, kind/feature, lgtm, release-note-none, size/L
