Repository caicloud/cyclone, pull requests merged in 2020-04, with the labels that each got.

#1400 refactor: use mkdir to acquire lock in svn resolver
  build/resolver/svn/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1399 fix: update deployment version to satisfy k8s 1.17
  pkg/server/biz/usage/watcher.go
  pkg/server/biz/usage/watcher_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note, size/S

#1401 fix: arm64 for docker and jq
  build/cicd/sonarqube/Dockerfile.arm64
  build/resolver/image/Dockerfile.arm64
  build/workflow/coordinator/Dockerfile.arm64
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1406 refact(*): use children descriptor to simplify api definition
  pkg/server/apis/v1alpha1/descriptors/integration.go
  pkg/server/apis/v1alpha1/descriptors/project.go
  pkg/server/apis/v1alpha1/descriptors/storage.go
  pkg/server/apis/v1alpha1/descriptors/workflow.go
  pkg/server/apis/v1alpha1/descriptors/workflowrun.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#1405 feat: support matching files by find_options for http resource
  build/resolver/http/entrypoint.sh
  pkg/server/biz/usage/watcher_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1407 refactor: provide cyclone base images to build images
  Makefile
  build/base/alpine/Dockerfile
  build/base/alpine/Dockerfile.arm64
  build/base/openjdk/Dockerfile
  build/base/openjdk/Dockerfile.arm64
  build/base/openjdk/sonar-runner.properties
  build/cicd/cd/Dockerfile
  build/cicd/cd/Dockerfile.arm64
  build/cicd/sonarqube/Dockerfile
  build/cicd/sonarqube/Dockerfile.arm64
  build/resolver/git/Dockerfile
  build/resolver/git/Dockerfile.arm64
  build/resolver/image/Dockerfile
  build/resolver/image/Dockerfile.arm64
  build/resolver/svn/Dockerfile
  build/resolver/svn/Dockerfile.arm64
  build/server/Dockerfile
  build/server/Dockerfile.arm64
  build/toolbox/Dockerfile
  build/toolbox/Dockerfile.arm64
  build/watcher/Dockerfile
  build/watcher/Dockerfile.arm64
  build/workflow/controller/Dockerfile
  build/workflow/controller/Dockerfile.arm64
  build/workflow/coordinator/Dockerfile
  build/workflow/coordinator/Dockerfile.arm64
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1410 fix: init caches cleanup status
  cmd/server/main.go
  pkg/meta/labels.go
  pkg/server/biz/accelerator/cleaner/clean.go
  pkg/server/biz/accelerator/cleaner/clean_test.go
  pkg/server/biz/pvc/pvc.go
  pkg/server/biz/usage/watcher.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1397 [HAIER-89]fix(cyclone):merge with tag v0.9.8, update to v0.9.8-alpha-oem-hr-4
  build/resolver/svn/Dockerfile
  cmd/server/main.go
  pkg/server/config/config.go
  pkg/util/k8s/client.go
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1412 chore(*): bump kubernetes version to 1.17.5
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/util/connrotation/connrotation.go
  vendor/modules.txt
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1413 chore(*): bump gorilla websocket version to 1.4.2
  go.mod
  go.sum
  vendor/github.com/gorilla/websocket/.travis.yml
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/doc.go
  vendor/github.com/gorilla/websocket/go.mod
  vendor/github.com/gorilla/websocket/go.sum
  vendor/github.com/gorilla/websocket/join.go
  vendor/github.com/gorilla/websocket/prepared.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/modules.txt
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1411 fix: process trivial stage cancellation
  pkg/workflow/workflowrun/utils.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
