Repository caicloud/cyclone, pull requests merged in 2020-05, with the labels that each got.

#1421 feat: cyclone server add health check
  cmd/server/main.go
  go.mod
  go.sum
  release/cyclone-server.yaml
  vendor/github.com/caicloud/nirvana/go.mod
  vendor/github.com/caicloud/nirvana/go.sum
  vendor/github.com/caicloud/nirvana/plugins/healthcheck/healthz.go
  vendor/modules.txt
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1414 fix: delete old cache cleanup pod while server restart
  pkg/server/biz/accelerator/cleaner/clean.go
  pkg/server/biz/accelerator/cleaner/clean_test.go
  pkg/server/biz/artifact/testdata/tenant1/project1/wf1/wfr1/artifacts/stage1/artifacts.tar
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1422 fix: sending ping message for websocket
  build/toolbox/resolver-runner.sh
  cmd/workflow/coordinator/main.go
  pkg/common/signals/signal.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/util/websocket/websocket.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/cycloneserver/client.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1420 [cps-2.8]:fix: sending ping message for websocket
  build/toolbox/resolver-runner.sh
  cmd/workflow/coordinator/main.go
  pkg/common/signals/signal.go
  pkg/server/handler/v1alpha1/workflowrun.go
  pkg/util/websocket/websocket.go
  pkg/workflow/coordinator/coordinator.go
  pkg/workflow/coordinator/cycloneserver/client.go
  pkg/workflow/coordinator/k8sapi/k8sapi.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1432 [cpd-2.8]feat: Global variable
  docs/concepts/values.md
  pkg/apis/cyclone/v1alpha1/workflow.go
  pkg/apis/cyclone/v1alpha1/workflow_run.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/common/values/generators.go
  pkg/common/values/generators_test.go
  pkg/common/values/nowtime.go
  pkg/common/values/nowtime_test.go
  pkg/common/values/random.go
  pkg/common/values/random_test.go
  pkg/server/handler/v1alpha1/notification.go
  pkg/workflow/controller/handlers/workflowrun/handler.go
  pkg/workflow/values/ref/ref.go
  pkg/workflow/values/ref/ref_test.go
  pkg/workflow/values/ref/secret.go
  pkg/workflow/values/ref/secret_test.go
  pkg/workflow/values/ref/stage.go
  pkg/workflow/values/ref/variable.go
  pkg/workflow/values/ref/variable_test.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/secret_test.go
  pkg/workflow/workload/pod/util.go
  pkg/workflow/workload/pod/util_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL
