Repository caicloud/cyclone, pull requests merged in 2020-02, with the labels that each got.

#1366 [cps-2.8]chore(release): adjust qps and burst for kube client
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1367 chore(release): adjust qps and burst for kube client
  release/cyclone-server.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1364 refactor(git): use openssl for git
  build/resolver/git/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1370 fix: AddKnownTypes: XxxList{}
  pkg/apis/cyclone/v1alpha1/register.go
  pkg/apis/cyclone/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cyclone/v1alpha1/zz_generated.defaults.go
  pkg/k8s/clientset/clientset.go
  pkg/k8s/clientset/doc.go
  pkg/k8s/clientset/fake/clientset_generated.go
  pkg/k8s/clientset/fake/doc.go
  pkg/k8s/clientset/fake/register.go
  pkg/k8s/clientset/scheme/doc.go
  pkg/k8s/clientset/scheme/register.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/cyclone_client.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/doc.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/executioncluster.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/doc.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_cyclone_client.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_executioncluster.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_project.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_resource.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_stage.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_workflow.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_workflowrun.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/fake/fake_workflowtrigger.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/generated_expansion.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/project.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/resource.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/stage.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/workflow.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/workflowrun.go
  pkg/k8s/clientset/typed/cyclone/v1alpha1/workflowtrigger.go
  pkg/k8s/informers/cyclone/interface.go
  pkg/k8s/informers/cyclone/v1alpha1/executioncluster.go
  pkg/k8s/informers/cyclone/v1alpha1/interface.go
  pkg/k8s/informers/cyclone/v1alpha1/project.go
  pkg/k8s/informers/cyclone/v1alpha1/resource.go
  pkg/k8s/informers/cyclone/v1alpha1/stage.go
  pkg/k8s/informers/cyclone/v1alpha1/workflow.go
  pkg/k8s/informers/cyclone/v1alpha1/workflowrun.go
  pkg/k8s/informers/cyclone/v1alpha1/workflowtrigger.go
  pkg/k8s/informers/factory.go
  pkg/k8s/informers/generic.go
  pkg/k8s/listers/cyclone/v1alpha1/executioncluster.go
  pkg/k8s/listers/cyclone/v1alpha1/expansion_generated.go
  pkg/k8s/listers/cyclone/v1alpha1/project.go
  pkg/k8s/listers/cyclone/v1alpha1/resource.go
  pkg/k8s/listers/cyclone/v1alpha1/stage.go
  pkg/k8s/listers/cyclone/v1alpha1/workflow.go
  pkg/k8s/listers/cyclone/v1alpha1/workflowrun.go
  pkg/k8s/listers/cyclone/v1alpha1/workflowtrigger.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1371 feat: push image with retry logic
  build/resolver/image/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1378 refactor: use alpine base image for watcher
  build/watcher/Dockerfile
  build/watcher/pvc-watcher.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1375 chore: normalize makefile
  Makefile
  hack/read_cpus_available.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1377 refactor(svn): use alpine base image for svn
  build/resolver/svn/Dockerfile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1387 [cps-2.8]chore: normalize makefile
  Makefile
  hack/read_cpus_available.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1389 [cps-2.9]chore: normalize makefile
  Makefile
  hack/read_cpus_available.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L
