Repository caicloud/cyclone, pull requests merged in 2020-09, with the labels that each got.

#1484 fix(gogs): change errors type to nirvana error
  pkg/server/biz/scm/gogs/gogs.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1481 feat: support sbt accelerate
  pkg/server/biz/accelerator/accelerate.go
  pkg/server/biz/accelerator/accelerate_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1491 [cps-2.8]fix: bump git version to 2.26.2 (#1475)
  Makefile
  build/base/alpine/Dockerfile
  build/base/alpine/Dockerfile.arm64
  build/cicd/cd/Dockerfile
  build/cicd/cd/Dockerfile.arm64
  build/resolver/git/Dockerfile
  build/resolver/git/Dockerfile.arm64
  build/resolver/image/Dockerfile
  build/resolver/image/Dockerfile.arm64
  build/resolver/svn/Dockerfile
  build/resolver/svn/Dockerfile.arm64
  build/server/Dockerfile
  build/server/Dockerfile.arm64
  build/toolbox/Dockerfile
  build/toolbox/Dockerfile.arm64
  build/watcher/Dockerfile
  build/watcher/Dockerfile.arm64
  build/workflow/controller/Dockerfile
  build/workflow/controller/Dockerfile.arm64
  build/workflow/coordinator/Dockerfile
  build/workflow/coordinator/Dockerfile.arm64
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1480 fix: should not mutate users input silently
  pkg/server/biz/scm/gitlab/gitlab.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1482 fix: optimize git clone process
  build/resolver/git/entrypoint.sh
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1485 feat: support bitbucket triggers workflows by hooks
  pkg/server/biz/scm/bitbucket/bitbucket.go
  pkg/server/biz/scm/bitbucket/server/server.go
  pkg/server/biz/scm/bitbucket/server/webhooks.go
  pkg/server/config/config.go
  pkg/server/handler/v1alpha1/integration.go
  pkg/server/handler/v1alpha1/tenant.go
  pkg/server/handler/v1alpha1/webhook.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1497 chore: fix typo of gitlab error message
  pkg/server/biz/scm/gitlab/gitlab.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#1500 fix: validate scm auth info problem
  pkg/server/biz/scm/scm.go
  pkg/util/cerr/error.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#1483 fix: connection refused should not block close cluster
  pkg/server/biz/integration/cluster/cluster.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#1506 fix: add workflow name info for pods created by cyclone
  pkg/workflow/common/const.go
  pkg/workflow/common/owner.go
  pkg/workflow/common/owner_test.go
  pkg/workflow/workflowrun/operator.go
  pkg/workflow/workload/pod/builder.go
  pkg/workflow/workload/pod/builder_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#1505 chore: update release yaml for infra
  release/cyclone-server.yaml
  release/workflow-controller.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S
